In [57]:
from splinter import Browser
from bs4 import BeautifulSoup
import pandas as pd
import pymongo 
import requests
from config import api_key
from selenium import webdriver
import datetime as dt
from datetime import datetime,timedelta
import numpy as np

In [ ]:
#executable_path = {'executable_path': '/usr/local/bin/chromedriver'}
#browser = Browser('chrome', **executable_path, headless=False)

In [2]:
# need to download the update version of chromedriver in order to match the chrome browser //
executable_path = {'executable_path': '/Users/moo/Desktop/final_project/chromedriver'}
browser = Browser('chrome', **executable_path, headless=True)

In [ ]:
#url = 'https://www.indeed.com/jobs?q=Data&l=CA&radius=5000'
#browser.visit(url)

In [3]:
#URL is from indeed.com
url='https://www.indeed.com/jobs?q=data%20analyst&l=CA&radius=150'
browser.visit(url)

In [4]:
html = browser.html

In [5]:
soup = BeautifulSoup(html, 'html.parser')

In [6]:
titles = soup.find_all("h2", class_ = "title")
print(titles)

[<h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/pagead/clk?mo=r&amp;ad=-6NYlbfkN0C_tipY1ZwG7sCobhyyJurqJgYPVEH0mlMozCYfasz-C01CEvU7-9J2iBUhEbDuhtt9lFI7napTJAmqcbh4N-IhDM0_-LWQn2EnVdkEiUfqqdNRfoPCn06RnsveejMBq2x-SOn6rZcDV8uUsGTX6oEOiGwtr1UJ9H4tvqrc494Qx_u1sWoTmU_hz4NFwkiaQV87Gq1wFWo7Ypt_s36ZopkfW67DFmcZPd9YA6ea5eeGPeifm3lSOBo5X-kUETxe0lxS77e_AX-VvV7sRAvHKbYUOWFX5hLLayjVpU7O54j24DpG7JZOi7egyA8edI1OV-YCDLDpvUU0G6klUE7Cvjj2SGpP9smQ1B8vmpKY6sAP0j6xryZhKmzPc1e2GQZpHPloJXBVCElKbUxffLQoNhmFkiIrVnNwxcElPCNkVS94_MQ1ZIkLwlD-6JOV7UbyViXT-BcIcSdT5Q==&amp;p=0&amp;fvj=1&amp;vjs=3" id="sja0" onclick="setRefineByCookie(['radius']); sjoc('sja0', 1); convCtr('SJ'); rclk(this,jobmap[0],true,1);" onmousedown="sjomd('sja0'); clk('sja0'); rclk(this,jobmap[0],1);" rel="noopener nofollow" target="_blank" title="Business Systems Data Analyst">
Business Systems <b>Data</b> <b>Analyst</b></a>
<span class="new">new</span></h2>, <h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/pagead/clk?mo=r&amp;ad=-6NYlbfkN0DUJBXYOpgsJ2dLqjv0OiO4Xd9wW0P3bw291DOOo5GVJd9z47qYropXA9jcltQlWi8hWsx-c3Q9T6NvXkrK6ASYbYhZn4BQ9qJ5pr73rVoJIEa6E1GDh1uTz1s5xxTQ3-GG5-s4kVRepXVuED1uKhHhILpeOc3Rjq6eh3LaEZaj_LPl511pnHqS9m7xmUXyBLUSyg88BHUzIMqIUAeeRHoI1HOfbM8Z6HyHhEyaf8JaJk3ZAEnrWsQMLZSDvIrhtMSm4Y7gGIbEBFFklWA5r79YsRlCJaRHwtGA5TkzwlbLYuN54q96fTNokgHvaeujEPkxF8_IEPvLwkrBcR5abQzyqWD3IxglZ3P6e6XhPBGc3ljjKS7yzif03ObSqCbNfIhmay3mo7jpN3ndJlCnPkpH_-rVjtQOWGFNNslInqNr16LVsONcaWZdXavbb0WHOi32QCevjrsvc1M9mCzwN2l2FUoPp4tTtP8=&amp;p=1&amp;fvj=1&amp;vjs=3" id="sja1" onclick="setRefineByCookie(['radius']); sjoc('sja1', 1); convCtr('SJ'); rclk(this,jobmap[1],true,1);" onmousedown="sjomd('sja1'); clk('sja1'); rclk(this,jobmap[1],1);" rel="noopener nofollow" target="_blank" title="Senior Data Analyst (Healthcare and HEDIS experience)">
Senior <b>Data</b> <b>Analyst</b> (Healthcare and HEDIS experience)</a>
</h2>, <h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/pagead/clk?mo=r&amp;ad=-6NYlbfkN0CXh-hjwU4T7GxgnpNLLYw0FI0Ew_VYvqPQQu_O9Dw_aT73eo3mfVckYK_YhIBpFVowX7cB8Xf29yqLVXrJux4ZYzz1nLs0JMBQMf3yKxYaxohSvk5l3sgBn-v87FJ2xM68JyjqYhhv6dA87mPSspXqJ2PR0Zrw0MuKmN0IeOnkVKJ4fKLo_yzyvI9qCzwBXZpUYoajx1cO7tgS-q4XGYk6vVGPcOGuk3ip-QmJ4rWtp-b2UWrZaKeyv82SDIxYiPNRI8qhLTZAsmGPhTojodoTzjtA_cq35fhljZc2mRHUVTIALwuS9jZsoYTj4sn8cyyZ8YSLJhBVasbZvI7JKuuCIPnxuh7NsLIfd2XDfS66V-wJwzFL7EKO4NFiaY10c4eG1e7TMTp6sN_rvcAco7OjHVo4npltAPklCDt49-R4VbJ7AVqC8DM-&amp;p=2&amp;fvj=1&amp;vjs=3" id="sja2" onclick="setRefineByCookie(['radius']); sjoc('sja2', 0); convCtr('SJ'); rclk(this,jobmap[2],true,0);" onmousedown="sjomd('sja2'); clk('sja2'); rclk(this,jobmap[2],0);" rel="noopener nofollow" target="_blank" title="Data Analyst">
<b>Data</b> <b>Analyst</b></a>
</h2>, <h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/pagead/clk?mo=r&amp;ad=-6NYlbfkN0CT8vBT9H5mqECx2dfLV_FONLPDKpIRssxVwtj05Tmm4qxTAI2czriaY4YcQXrGzkFINLNNhMX5NLEAUm10sqvT4SLCyF1imactvfLkGhtER4yMPmsOjZECUjngRX3NVJDqFpCUEs9mnmZ2LqhvvKWfaGb4Sa4rop_Tx1_0o2qD7qUDcsoxPMb4doK4M1ZsAcmnN99g1xNpvNP1mw09ED87PzJUEknBgzNmMjM3g6tRztxx0zbn0ELN-tD6VMfKGnrQZbj2zhB-30XhR6Mb3P0vqC6TJZ05R3ocOJSNxl0DQRfQLpigcRH-PbxDCR-kvyoM7S22BfFS6yb601flF6TsahreE7YAi8whZCn0OEOHm3pLfCU3aYIS2sgjWFGKFp6TakNPe8hrL0pkRtLXkmCqkpKyqtCagsFANyIZ8vtgk_nLqERV5UnW9SL0nKeD8B_OWq37BULjn_1Ttu_oyCOvUvwiVmMqb7NnVZ7_CN9E-YDLX1J0U5fZe26iOLyWWRyL6E_xv5WZBPa02CXzRclO-rRv9ol43Vla88vDqSBqfjT2C4fSTJ_lQ33_KUIeiyYztoODOke50hkYVsffS2JSY_YfFzoGYjCzdPgD9dpsZndfQUk53JUmKBYcbL4wcRWQEujsDQ6gisfxVAPuI0JaSx6iIw7d2oTiEIRaTgQgKLN5hU-j3MNSI6_KyT_VzKwst1umGgj6DSWVduPni0Udgb34jbz24G0Z16KTYZvZD3afLK7_HPTXNVtlDZxdIJBLiGPT2DzZp-pYhu3-hVbmsh7KuNs8ipWmEFB1tvzeyrulehblvqLriV_YKi8_TYGGmsJGSHQlsKudIPxM9vBOI7KKmrhirnp6xTeQF8NSk9FzxMx47c3hIN9--1oAhO4KynTIPW4v_uaIjXcqnPyW8wHv_uoNxEJ8V8T4HbDq-wOfwYfMnX5V-9OCogdoPGk=&amp;p=3&amp;fvj=0&amp;vjs=3" id="sja3" onclick="setRefineByCookie(['radius']); sjoc('sja3', 0); convCtr('SJ'); rclk(this,jobmap[3],true,0);" onmousedown="sjomd('sja3'); clk('sja3'); rclk(this,jobmap[3],0);" rel="noopener nofollow" target="_blank" title="Data Analyst - 017832">
<b>Data</b> <b>Analyst</b> - 017832</a>
<span class="new">new</span></h2>, <h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/rc/clk?jk=5ffbd412f7c81170&amp;fccid=df420c31dd6f3188&amp;vjs=3" id="jl_5ffbd412f7c81170" onclick="setRefineByCookie(['radius']); return rclk(this,jobmap[4],true,0);" onmousedown="return rclk(this,jobmap[4],0);" rel="noopener nofollow" target="_blank" title="Data Analyst">
<b>Data</b> <b>Analyst</b></a>
<span class="new">new</span></h2>, <h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/pagead/clk?mo=r&amp;ad=-6NYlbfkN0AGjFLEqiUCO6PVLg8_TBDyekOR61XST_scoMotBQ1lfoenjoIuKg3_UO7yYVREbCLBzSxA09Sxfi_Obf6LGlnF_q00BSa57yw4zOcLa7XpDpmPy72TPCSxd6CQNRrgCBRUFachAKP8vv8MlIcBz2QspdUfXBVLkeYxox1uF2oUHADFijkZViPfVLgY62_JPy2OgOA2VzzUeibIeie1h9v0xjfh9vX2wTqcg7Mn1ieHB_67KqiJ0meoRq1MSiVOjnzgzLD2DdOHsDeNJU6gPMkMhtr0XpLa6_DcNSThk3tikuM8DesrtRpn6VajX9yLshQefftGV_ly_seVajHz7C82LjahN47txdFSCmwWF6mHA2UWtgP_2SRtkhzSPZ9JU_SSLMv95mQiFf6oYf4__iM1aLTTGfN35Pj0YU5iVmLwfp6I5DxI5rq1Um47n1vmy3k=&amp;p=5&amp;fvj=1&amp;vjs=3" id="sja5" onclick="setRefineByCookie(['radius']); sjoc('sja5', 1); convCtr('SJ'); rclk(this,jobmap[5],true,1);" onmousedown="sjomd('sja5'); clk('sja5'); rclk(this,jobmap[5],1);" rel="noopener nofollow" target="_blank" title="Data Analyst">
<b>Data</b> <b>Analyst</b></a>
</h2>, <h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/rc/clk?jk=a6a3a139f891dc96&amp;fccid=f50928466f72fdbe&amp;vjs=3" id="jl_a6a3a139f891dc96" onclick="setRefineByCookie(['radius']); return rclk(this,jobmap[6],true,0);" onmousedown="return rclk(this,jobmap[6],0);" rel="noopener nofollow" target="_blank" title="Marketing Specialist &amp; Data Analyst">
Marketing Specialist &amp; <b>Data</b> <b>Analyst</b></a>
<span class="new">new</span></h2>, <h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/pagead/clk?mo=r&amp;ad=-6NYlbfkN0DV31niWqDtTHeOnkyzmrsZQOR3rxhS34GQbXZlnCN9Svco2UvkMX7_lIMixVkZLVjd85VGk8xhXuPCXIE4clbIDnYT0rY4NVYwqaMW_1jn74MZK3UCjLtTJK_rAZJ8VtXHA8_8JH2X7mgxLiME6tudpXT2WAe5KPS0TIeG0ZB6eN8_mAqVfB3bOgk6GhR7khYvxTam6P0osqZn3SPfk0kgN3crcqgDmCWOtAobDdaVfedAfAXPZH9akQ0FhtCY9N0QiemrXcM47Gd_Atq6J1GDTzR1F_LYTkVYE1S6h2MYnlQ6SB34mLI1joFlnmK1BVTAdomU6xg8r8vkmptKilMnrl98-GIn-0_1PEHg_jie-HDhhk7OQwiWx4d4x8souYOSNWKugaApDeR69Q4DSR3lmllVD3Zif1DWXnBiY6rUpp4U4I1yxt8QLxW-AQ0CLrVCzLgWqJHkSETnZVhXGqBN2Fo8qP-uOlcY_CsLBC83EEKdfRCao3wd80Wf2U0Hdb4g6yXKUcvjGaYB3eyQ9fYrtHaW7K6dt4Csx6qeeYhUYe6pmv06vErXSAvxYc_-3gSg827gvBCQp9Yqao6dJxVEeHY3UxHdRNCLZMwvBeUAb76O1KvPN5JxKotLkjQCrkgNjlKSWNiHTwSlHRbl1OJG1cTyKNDU6L3oosqeAP0zzjOjPXxI-KHpiNYB_JzZb4-AV8JiA7LIOzn3_-l_ulOQQHWMOZLO86643K-LZK3f2r_fKEmtqVWbKPx15Huu_jgc5oESu66Jz7SckPjdfJAQOyw35jfOos9Ld8CFGWMnHB3qsm85OAmlKQCgIWPMzZHFxckL2PzUmNFnwkdMPS2luQ7HkiR-eHwScaVw80G6ahMyR5ZuT9b_reT1nUC30G4OjXzAlQdgFszOPjcfieDrvukOlUwcMSDnHxPCgjMhvkjGnrnmEcgQ9hh2Jfu9wnjDSkAsb5XO3i2Bb5PkUKJKAuGO-qfHd0CjQ2Nb3S7NYk6rOytCIgVLkBihXa069yS0YjbR7b5TzN-3dH1aGaUUcUXEJtKcP7jhFTal4SsZo0QaguQa-KomXDRHNqu6VYY=&amp;p=7&amp;fvj=0&amp;vjs=3" id="sja7" onclick="setRefineByCookie(['radius']); sjoc('sja7', 0); convCtr('SJ'); rclk(this,jobmap[7],true,0);" onmousedown="sjomd('sja7'); clk('sja7'); rclk(this,jobmap[7],0);" rel="noopener nofollow" target="_blank" title="Data Analyst">
<b>Data</b> <b>Analyst</b></a>
</h2>, <h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/rc/clk?jk=8b95e3d5285db46a&amp;fccid=96ec40301af52908&amp;vjs=3" id="jl_8b95e3d5285db46a" onclick="setRefineByCookie(['radius']); return rclk(this,jobmap[8],true,0);" onmousedown="return rclk(this,jobmap[8],0);" rel="noopener nofollow" target="_blank" title="Sales Data Analyst">
Sales <b>Data</b> <b>Analyst</b></a>
<span class="new">new</span></h2>, <h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/rc/clk?jk=3fb21f8853e8b9da&amp;fccid=350a6f39794d6376&amp;vjs=3" id="jl_3fb21f8853e8b9da" onclick="setRefineByCookie(['radius']); return rclk(this,jobmap[9],true,1);" onmousedown="return rclk(this,jobmap[9],1);" rel="noopener nofollow" target="_blank" title="Data Analyst">
<b>Data</b> <b>Analyst</b></a>
<span class="new">new</span></h2>, <h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/company/Helm360/jobs/Junior-Data-Analyst-292d5f3d723fafb5?fccid=0d0582f3e490bc41&amp;vjs=3" id="jl_292d5f3d723fafb5" onclick="setRefineByCookie(['radius']); return rclk(this,jobmap[10],true,1);" onmousedown="return rclk(this,jobmap[10],1);" rel="noopener nofollow" target="_blank" title="Junior Data Analyst">
Junior <b>Data</b> <b>Analyst</b></a>
</h2>, <h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/rc/clk?jk=bcc638c267d6d6ea&amp;fccid=85ffffaebf673194&amp;vjs=3" id="jl_bcc638c267d6d6ea" onclick="setRefineByCookie(['radius']); return rclk(this,jobmap[11],true,0);" onmousedown="return rclk(this,jobmap[11],0);" rel="noopener nofollow" target="_blank" title="Data Analyst II">
<b>Data</b> <b>Analyst</b> II</a>
<span class="new">new</span></h2>, <h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/company/Biocept,-Inc./jobs/Data-Analyst-Temporary-743c2899d491f994?fccid=703a99e5c45f92d5&amp;vjs=3" id="jl_743c2899d491f994" onclick="setRefineByCookie(['radius']); return rclk(this,jobmap[12],true,0);" onmousedown="return rclk(this,jobmap[12],0);" rel="noopener nofollow" target="_blank" title="Data Analyst Temporary">
<b>Data</b> <b>Analyst</b> Temporary</a>
<span class="new">new</span></h2>, <h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/company/Pyramid/jobs/Junior-Data-Analyst-b3afaf6ef89ca4fa?fccid=7b98e1432e30395f&amp;vjs=3" id="jl_b3afaf6ef89ca4fa" onclick="setRefineByCookie(['radius']); return rclk(this,jobmap[13],true,1);" onmousedown="return rclk(this,jobmap[13],1);" rel="noopener nofollow" target="_blank" title="Jr. Data Analyst">
Jr. <b>Data</b> <b>Analyst</b></a>
</h2>, <h2 class="title">
<a class="jobtitle turnstileLink" data-tn-element="jobTitle" href="/rc/clk?jk=48a2dc8a62fc54a3&amp;fccid=c659788ec6cc356e&amp;vjs=3" id="jl_48a2dc8a62fc54a3" onclick="setRefineByCookie(['radius']); return rclk(this,jobmap[14],true,0);" onmousedown="return rclk(this,jobmap[14],0);" rel="noopener nofollow" target="_blank" title="Data Operations Analyst">
<b>Data</b> Operations <b>Analyst</b></a>
<span class="new">new</span></h2>]

#  we are going to scrape 1-10 web pages info from indeed.com for Date Analyst Job.
#  in order to create our own dataset
#  the columns we wanted :
# job_title, job_location,salary,city,posted_date

In [7]:
# Scraping data from the indeed website //
for title in titles:
    job_title = title.get_text()
    print(job_title)

Business Systems Data Analyst
new


Senior Data Analyst (Healthcare and HEDIS experience)



Data Analyst



Data Analyst - 017832
new


Data Analyst
new


Data Analyst



Marketing Specialist & Data Analyst
new


Data Analyst



Sales Data Analyst
new


Data Analyst
new


Junior Data Analyst



Data Analyst II
new


Data Analyst Temporary
new


Jr. Data Analyst



Data Operations Analyst
new

In [8]:
#### from page 1-10data



job_titles = [0]
 
 # gether the job results /// from 1-10 pages  
for x in range(1, 11):
    titles = soup.find_all("h2", class_ = "title")
    for title in titles:
        job_titles.append(title.text)
        print('page:', x, '-------------')
        print(title.text)
        browser.find_by_xpath('/html/body/table[2]/tbody/tr/td/table/tbody/tr/td[1]/nav/div/ul/li[6]/a/span/span')

page: 1 -------------


Business Systems Data Analyst
new
page: 1 -------------


Senior Data Analyst (Healthcare and HEDIS experience)

page: 1 -------------


Data Analyst

page: 1 -------------


Data Analyst - 017832
new
page: 1 -------------


Data Analyst
new
page: 1 -------------


Data Analyst

page: 1 -------------


Marketing Specialist & Data Analyst
new
page: 1 -------------


Data Analyst

page: 1 -------------


Sales Data Analyst
new
page: 1 -------------


Data Analyst
new
page: 1 -------------


Junior Data Analyst

page: 1 -------------


Data Analyst II
new
page: 1 -------------


Data Analyst Temporary
new
page: 1 -------------


Jr. Data Analyst

page: 1 -------------


Data Operations Analyst
new
page: 2 -------------


Business Systems Data Analyst
new
page: 2 -------------


Senior Data Analyst (Healthcare and HEDIS experience)

page: 2 -------------


Data Analyst

page: 2 -------------


Data Analyst - 017832
new
page: 2 -------------


Data Analyst
new
page: 2 -------------


Data Analyst

page: 2 -------------


Marketing Specialist & Data Analyst
new
page: 2 -------------


Data Analyst

page: 2 -------------


Sales Data Analyst
new
page: 2 -------------


Data Analyst
new
page: 2 -------------


Junior Data Analyst

page: 2 -------------


Data Analyst II
new
page: 2 -------------


Data Analyst Temporary
new
page: 2 -------------


Jr. Data Analyst

page: 2 -------------


Data Operations Analyst
new
page: 3 -------------


Business Systems Data Analyst
new
page: 3 -------------


Senior Data Analyst (Healthcare and HEDIS experience)

page: 3 -------------


Data Analyst

page: 3 -------------


Data Analyst - 017832
new
page: 3 -------------


Data Analyst
new
page: 3 -------------


Data Analyst

page: 3 -------------


Marketing Specialist & Data Analyst
new
page: 3 -------------


Data Analyst

page: 3 -------------


Sales Data Analyst
new
page: 3 -------------


Data Analyst
new
page: 3 -------------


Junior Data Analyst

page: 3 -------------


Data Analyst II
new
page: 3 -------------


Data Analyst Temporary
new
page: 3 -------------


Jr. Data Analyst

page: 3 -------------


Data Operations Analyst
new
page: 4 -------------


Business Systems Data Analyst
new
page: 4 -------------


Senior Data Analyst (Healthcare and HEDIS experience)

page: 4 -------------


Data Analyst

page: 4 -------------


Data Analyst - 017832
new
page: 4 -------------


Data Analyst
new
page: 4 -------------


Data Analyst

page: 4 -------------


Marketing Specialist & Data Analyst
new
page: 4 -------------


Data Analyst

page: 4 -------------


Sales Data Analyst
new
page: 4 -------------


Data Analyst
new
page: 4 -------------


Junior Data Analyst

page: 4 -------------


Data Analyst II
new
page: 4 -------------


Data Analyst Temporary
new
page: 4 -------------


Jr. Data Analyst

page: 4 -------------


Data Operations Analyst
new
page: 5 -------------


Business Systems Data Analyst
new
page: 5 -------------


Senior Data Analyst (Healthcare and HEDIS experience)

page: 5 -------------


Data Analyst

page: 5 -------------


Data Analyst - 017832
new
page: 5 -------------


Data Analyst
new
page: 5 -------------


Data Analyst

page: 5 -------------


Marketing Specialist & Data Analyst
new
page: 5 -------------


Data Analyst

page: 5 -------------


Sales Data Analyst
new
page: 5 -------------


Data Analyst
new
page: 5 -------------


Junior Data Analyst

page: 5 -------------


Data Analyst II
new
page: 5 -------------


Data Analyst Temporary
new
page: 5 -------------


Jr. Data Analyst

page: 5 -------------


Data Operations Analyst
new
page: 6 -------------


Business Systems Data Analyst
new
page: 6 -------------


Senior Data Analyst (Healthcare and HEDIS experience)

page: 6 -------------


Data Analyst

page: 6 -------------


Data Analyst - 017832
new
page: 6 -------------


Data Analyst
new
page: 6 -------------


Data Analyst

page: 6 -------------


Marketing Specialist & Data Analyst
new
page: 6 -------------


Data Analyst

page: 6 -------------


Sales Data Analyst
new
page: 6 -------------


Data Analyst
new
page: 6 -------------


Junior Data Analyst

page: 6 -------------


Data Analyst II
new
page: 6 -------------


Data Analyst Temporary
new
page: 6 -------------


Jr. Data Analyst

page: 6 -------------


Data Operations Analyst
new
page: 7 -------------


Business Systems Data Analyst
new
page: 7 -------------


Senior Data Analyst (Healthcare and HEDIS experience)

page: 7 -------------


Data Analyst

page: 7 -------------


Data Analyst - 017832
new
page: 7 -------------


Data Analyst
new
page: 7 -------------


Data Analyst

page: 7 -------------


Marketing Specialist & Data Analyst
new
page: 7 -------------


Data Analyst

page: 7 -------------


Sales Data Analyst
new
page: 7 -------------


Data Analyst
new
page: 7 -------------


Junior Data Analyst

page: 7 -------------


Data Analyst II
new
page: 7 -------------


Data Analyst Temporary
new
page: 7 -------------


Jr. Data Analyst

page: 7 -------------


Data Operations Analyst
new
page: 8 -------------


Business Systems Data Analyst
new
page: 8 -------------


Senior Data Analyst (Healthcare and HEDIS experience)

page: 8 -------------


Data Analyst

page: 8 -------------


Data Analyst - 017832
new
page: 8 -------------


Data Analyst
new
page: 8 -------------


Data Analyst

page: 8 -------------


Marketing Specialist & Data Analyst
new
page: 8 -------------


Data Analyst

page: 8 -------------


Sales Data Analyst
new
page: 8 -------------


Data Analyst
new
page: 8 -------------


Junior Data Analyst

page: 8 -------------


Data Analyst II
new
page: 8 -------------


Data Analyst Temporary
new
page: 8 -------------


Jr. Data Analyst

page: 8 -------------


Data Operations Analyst
new
page: 9 -------------


Business Systems Data Analyst
new
page: 9 -------------


Senior Data Analyst (Healthcare and HEDIS experience)

page: 9 -------------


Data Analyst

page: 9 -------------


Data Analyst - 017832
new
page: 9 -------------


Data Analyst
new
page: 9 -------------


Data Analyst

page: 9 -------------


Marketing Specialist & Data Analyst
new
page: 9 -------------


Data Analyst

page: 9 -------------


Sales Data Analyst
new
page: 9 -------------


Data Analyst
new
page: 9 -------------


Junior Data Analyst

page: 9 -------------


Data Analyst II
new
page: 9 -------------


Data Analyst Temporary
new
page: 9 -------------


Jr. Data Analyst

page: 9 -------------


Data Operations Analyst
new
page: 10 -------------


Business Systems Data Analyst
new
page: 10 -------------


Senior Data Analyst (Healthcare and HEDIS experience)

page: 10 -------------


Data Analyst

page: 10 -------------


Data Analyst - 017832
new
page: 10 -------------


Data Analyst
new
page: 10 -------------


Data Analyst

page: 10 -------------


Marketing Specialist & Data Analyst
new
page: 10 -------------


Data Analyst

page: 10 -------------


Sales Data Analyst
new
page: 10 -------------


Data Analyst
new
page: 10 -------------


Junior Data Analyst

page: 10 -------------


Data Analyst II
new
page: 10 -------------


Data Analyst Temporary
new
page: 10 -------------


Jr. Data Analyst

page: 10 -------------


Data Operations Analyst
new

In [21]:
clean_job_titles = []

#loop through result
for job in job_titles[1:]:
    clean_job_title = job.replace('\n', '')
    clean_job_titles.append(clean_job_title)

In [22]:
print(clean_job_titles)

['Business Systems Data Analystnew', 'Senior Data Analyst (Healthcare and HEDIS experience)', 'Data Analyst', 'Data Analyst - 017832new', 'Data Analystnew', 'Data Analyst', 'Marketing Specialist & Data Analystnew', 'Data Analyst', 'Sales Data Analystnew', 'Data Analystnew', 'Junior Data Analyst', 'Data Analyst IInew', 'Data Analyst Temporarynew', 'Jr. Data Analyst', 'Data Operations Analystnew', 'Business Systems Data Analystnew', 'Senior Data Analyst (Healthcare and HEDIS experience)', 'Data Analyst', 'Data Analyst - 017832new', 'Data Analystnew', 'Data Analyst', 'Marketing Specialist & Data Analystnew', 'Data Analyst', 'Sales Data Analystnew', 'Data Analystnew', 'Junior Data Analyst', 'Data Analyst IInew', 'Data Analyst Temporarynew', 'Jr. Data Analyst', 'Data Operations Analystnew', 'Business Systems Data Analystnew', 'Senior Data Analyst (Healthcare and HEDIS experience)', 'Data Analyst', 'Data Analyst - 017832new', 'Data Analystnew', 'Data Analyst', 'Marketing Specialist & Data Analystnew', 'Data Analyst', 'Sales Data Analystnew', 'Data Analystnew', 'Junior Data Analyst', 'Data Analyst IInew', 'Data Analyst Temporarynew', 'Jr. Data Analyst', 'Data Operations Analystnew', 'Business Systems Data Analystnew', 'Senior Data Analyst (Healthcare and HEDIS experience)', 'Data Analyst', 'Data Analyst - 017832new', 'Data Analystnew', 'Data Analyst', 'Marketing Specialist & Data Analystnew', 'Data Analyst', 'Sales Data Analystnew', 'Data Analystnew', 'Junior Data Analyst', 'Data Analyst IInew', 'Data Analyst Temporarynew', 'Jr. Data Analyst', 'Data Operations Analystnew', 'Business Systems Data Analystnew', 'Senior Data Analyst (Healthcare and HEDIS experience)', 'Data Analyst', 'Data Analyst - 017832new', 'Data Analystnew', 'Data Analyst', 'Marketing Specialist & Data Analystnew', 'Data Analyst', 'Sales Data Analystnew', 'Data Analystnew', 'Junior Data Analyst', 'Data Analyst IInew', 'Data Analyst Temporarynew', 'Jr. Data Analyst', 'Data Operations Analystnew', 'Business Systems Data Analystnew', 'Senior Data Analyst (Healthcare and HEDIS experience)', 'Data Analyst', 'Data Analyst - 017832new', 'Data Analystnew', 'Data Analyst', 'Marketing Specialist & Data Analystnew', 'Data Analyst', 'Sales Data Analystnew', 'Data Analystnew', 'Junior Data Analyst', 'Data Analyst IInew', 'Data Analyst Temporarynew', 'Jr. Data Analyst', 'Data Operations Analystnew', 'Business Systems Data Analystnew', 'Senior Data Analyst (Healthcare and HEDIS experience)', 'Data Analyst', 'Data Analyst - 017832new', 'Data Analystnew', 'Data Analyst', 'Marketing Specialist & Data Analystnew', 'Data Analyst', 'Sales Data Analystnew', 'Data Analystnew', 'Junior Data Analyst', 'Data Analyst IInew', 'Data Analyst Temporarynew', 'Jr. Data Analyst', 'Data Operations Analystnew', 'Business Systems Data Analystnew', 'Senior Data Analyst (Healthcare and HEDIS experience)', 'Data Analyst', 'Data Analyst - 017832new', 'Data Analystnew', 'Data Analyst', 'Marketing Specialist & Data Analystnew', 'Data Analyst', 'Sales Data Analystnew', 'Data Analystnew', 'Junior Data Analyst', 'Data Analyst IInew', 'Data Analyst Temporarynew', 'Jr. Data Analyst', 'Data Operations Analystnew', 'Business Systems Data Analystnew', 'Senior Data Analyst (Healthcare and HEDIS experience)', 'Data Analyst', 'Data Analyst - 017832new', 'Data Analystnew', 'Data Analyst', 'Marketing Specialist & Data Analystnew', 'Data Analyst', 'Sales Data Analystnew', 'Data Analystnew', 'Junior Data Analyst', 'Data Analyst IInew', 'Data Analyst Temporarynew', 'Jr. Data Analyst', 'Data Operations Analystnew', 'Business Systems Data Analystnew', 'Senior Data Analyst (Healthcare and HEDIS experience)', 'Data Analyst', 'Data Analyst - 017832new', 'Data Analystnew', 'Data Analyst', 'Marketing Specialist & Data Analystnew', 'Data Analyst', 'Sales Data Analystnew', 'Data Analystnew', 'Junior Data Analyst', 'Data Analyst IInew', 'Data Analyst Temporarynew', 'Jr. Data Analyst', 'Data Operations Analystnew']

In [9]:
# Getting job location //
locations = soup.find_all("span", class_ = "location accessible-contrast-color-location")
locations

[<span class="location accessible-contrast-color-location">El Dorado Hills, CA 95762</span>,
 <span class="location accessible-contrast-color-location">Sacramento, CA 95827</span>,
 <span class="location accessible-contrast-color-location">Modesto, CA 95354</span>,
 <span class="location accessible-contrast-color-location">Morgan Hill, CA</span>,
 <span class="location accessible-contrast-color-location">Poway, CA 92064</span>,
 <span class="location accessible-contrast-color-location">Redwood City, CA 94063 <span style="font-size: smaller">(Downtown area)</span></span>,
 <span class="location accessible-contrast-color-location">San Diego, CA 92121 <span style="font-size: smaller">(Sorrento Valley area)</span></span>,
 <span class="location accessible-contrast-color-location">Pleasanton, CA</span>,
 <span class="location accessible-contrast-color-location">San Francisco, CA</span>]

In [10]:
# job location details ??? scaping //
#Empty list to append the result
job_locations = []


#loop through the returned result
for x in range(1, 11):
    locations = soup.find_all("span", class_ = "location accessible-contrast-color-location")
    for location in locations:
        job_locations.append(location.text)
        print('page:', x, '-------------')
        print(location.text)
        browser.find_by_xpath('/html/body/table[2]/tbody/tr/td/table/tbody/tr/td[1]/div[7]/div[1]/span[1]')

page: 1 -------------
El Dorado Hills, CA 95762
page: 1 -------------
Sacramento, CA 95827
page: 1 -------------
Modesto, CA 95354
page: 1 -------------
Morgan Hill, CA
page: 1 -------------
Poway, CA 92064
page: 1 -------------
Redwood City, CA 94063 (Downtown area)
page: 1 -------------
San Diego, CA 92121 (Sorrento Valley area)
page: 1 -------------
Pleasanton, CA
page: 1 -------------
San Francisco, CA
page: 2 -------------
El Dorado Hills, CA 95762
page: 2 -------------
Sacramento, CA 95827
page: 2 -------------
Modesto, CA 95354
page: 2 -------------
Morgan Hill, CA
page: 2 -------------
Poway, CA 92064
page: 2 -------------
Redwood City, CA 94063 (Downtown area)
page: 2 -------------
San Diego, CA 92121 (Sorrento Valley area)
page: 2 -------------
Pleasanton, CA
page: 2 -------------
San Francisco, CA
page: 3 -------------
El Dorado Hills, CA 95762
page: 3 -------------
Sacramento, CA 95827
page: 3 -------------
Modesto, CA 95354
page: 3 -------------
Morgan Hill, CA
page: 3 -------------
Poway, CA 92064
page: 3 -------------
Redwood City, CA 94063 (Downtown area)
page: 3 -------------
San Diego, CA 92121 (Sorrento Valley area)
page: 3 -------------
Pleasanton, CA
page: 3 -------------
San Francisco, CA
page: 4 -------------
El Dorado Hills, CA 95762
page: 4 -------------
Sacramento, CA 95827
page: 4 -------------
Modesto, CA 95354
page: 4 -------------
Morgan Hill, CA
page: 4 -------------
Poway, CA 92064
page: 4 -------------
Redwood City, CA 94063 (Downtown area)
page: 4 -------------
San Diego, CA 92121 (Sorrento Valley area)
page: 4 -------------
Pleasanton, CA
page: 4 -------------
San Francisco, CA
page: 5 -------------
El Dorado Hills, CA 95762
page: 5 -------------
Sacramento, CA 95827
page: 5 -------------
Modesto, CA 95354
page: 5 -------------
Morgan Hill, CA
page: 5 -------------
Poway, CA 92064
page: 5 -------------
Redwood City, CA 94063 (Downtown area)
page: 5 -------------
San Diego, CA 92121 (Sorrento Valley area)
page: 5 -------------
Pleasanton, CA
page: 5 -------------
San Francisco, CA
page: 6 -------------
El Dorado Hills, CA 95762
page: 6 -------------
Sacramento, CA 95827
page: 6 -------------
Modesto, CA 95354
page: 6 -------------
Morgan Hill, CA
page: 6 -------------
Poway, CA 92064
page: 6 -------------
Redwood City, CA 94063 (Downtown area)
page: 6 -------------
San Diego, CA 92121 (Sorrento Valley area)
page: 6 -------------
Pleasanton, CA
page: 6 -------------
San Francisco, CA
page: 7 -------------
El Dorado Hills, CA 95762
page: 7 -------------
Sacramento, CA 95827
page: 7 -------------
Modesto, CA 95354
page: 7 -------------
Morgan Hill, CA
page: 7 -------------
Poway, CA 92064
page: 7 -------------
Redwood City, CA 94063 (Downtown area)
page: 7 -------------
San Diego, CA 92121 (Sorrento Valley area)
page: 7 -------------
Pleasanton, CA
page: 7 -------------
San Francisco, CA
page: 8 -------------
El Dorado Hills, CA 95762
page: 8 -------------
Sacramento, CA 95827
page: 8 -------------
Modesto, CA 95354
page: 8 -------------
Morgan Hill, CA
page: 8 -------------
Poway, CA 92064
page: 8 -------------
Redwood City, CA 94063 (Downtown area)
page: 8 -------------
San Diego, CA 92121 (Sorrento Valley area)
page: 8 -------------
Pleasanton, CA
page: 8 -------------
San Francisco, CA
page: 9 -------------
El Dorado Hills, CA 95762
page: 9 -------------
Sacramento, CA 95827
page: 9 -------------
Modesto, CA 95354
page: 9 -------------
Morgan Hill, CA
page: 9 -------------
Poway, CA 92064
page: 9 -------------
Redwood City, CA 94063 (Downtown area)
page: 9 -------------
San Diego, CA 92121 (Sorrento Valley area)
page: 9 -------------
Pleasanton, CA
page: 9 -------------
San Francisco, CA
page: 10 -------------
El Dorado Hills, CA 95762
page: 10 -------------
Sacramento, CA 95827
page: 10 -------------
Modesto, CA 95354
page: 10 -------------
Morgan Hill, CA
page: 10 -------------
Poway, CA 92064
page: 10 -------------
Redwood City, CA 94063 (Downtown area)
page: 10 -------------
San Diego, CA 92121 (Sorrento Valley area)
page: 10 -------------
Pleasanton, CA
page: 10 -------------
San Francisco, CA

In [11]:
# salaryyyyyyyy
salary = soup.find_all("span", class_ = "salary")
salary

[<span class="salary no-wrap">
 <span class="salaryText">
 Up to $80,000 a year</span>
 </span>,
 <span class="salary no-wrap">
 <span class="salaryText">
 $90,000 - $100,000 a year</span>
 </span>,
 <span class="salary no-wrap">
 <span class="salaryText">
 $70,000 - $85,000 a year</span>
 </span>,
 <span class="salary no-wrap">
 <span class="salaryText">
 $64,800 - $73,200 a year</span>
 </span>,
 <span class="salary no-wrap">
 <span class="salaryText">
 $80,000 - $90,000 a year</span>
 </span>,
 <span class="salary no-wrap">
 <span class="salaryText">
 $19 - $26 an hour</span>
 </span>]

In [12]:
job_salary = []


#loop through the returned result
for x in range(1, 11):
    salary = soup.find_all("span", class_ = "salary")
    for s in salary:
        job_salary.append(s.text)
        print('page:', x, '-------------')
        print(s.text)
        browser.find_by_xpath('/html/body/table[2]/tbody/tr/td/table/tbody/tr/td[1]/div[7]/div[1]/span[1]')

page: 1 -------------


Up to $80,000 a year

page: 1 -------------


$90,000 - $100,000 a year

page: 1 -------------


$70,000 - $85,000 a year

page: 1 -------------


$64,800 - $73,200 a year

page: 1 -------------


$80,000 - $90,000 a year

page: 1 -------------


$19 - $26 an hour

page: 2 -------------


Up to $80,000 a year

page: 2 -------------


$90,000 - $100,000 a year

page: 2 -------------


$70,000 - $85,000 a year

page: 2 -------------


$64,800 - $73,200 a year

page: 2 -------------


$80,000 - $90,000 a year

page: 2 -------------


$19 - $26 an hour

page: 3 -------------


Up to $80,000 a year

page: 3 -------------


$90,000 - $100,000 a year

page: 3 -------------


$70,000 - $85,000 a year

page: 3 -------------


$64,800 - $73,200 a year

page: 3 -------------


$80,000 - $90,000 a year

page: 3 -------------


$19 - $26 an hour

page: 4 -------------


Up to $80,000 a year

page: 4 -------------


$90,000 - $100,000 a year

page: 4 -------------


$70,000 - $85,000 a year

page: 4 -------------


$64,800 - $73,200 a year

page: 4 -------------


$80,000 - $90,000 a year

page: 4 -------------


$19 - $26 an hour

page: 5 -------------


Up to $80,000 a year

page: 5 -------------


$90,000 - $100,000 a year

page: 5 -------------


$70,000 - $85,000 a year

page: 5 -------------


$64,800 - $73,200 a year

page: 5 -------------


$80,000 - $90,000 a year

page: 5 -------------


$19 - $26 an hour

page: 6 -------------


Up to $80,000 a year

page: 6 -------------


$90,000 - $100,000 a year

page: 6 -------------


$70,000 - $85,000 a year

page: 6 -------------


$64,800 - $73,200 a year

page: 6 -------------


$80,000 - $90,000 a year

page: 6 -------------


$19 - $26 an hour

page: 7 -------------


Up to $80,000 a year

page: 7 -------------


$90,000 - $100,000 a year

page: 7 -------------


$70,000 - $85,000 a year

page: 7 -------------


$64,800 - $73,200 a year

page: 7 -------------


$80,000 - $90,000 a year

page: 7 -------------


$19 - $26 an hour

page: 8 -------------


Up to $80,000 a year

page: 8 -------------


$90,000 - $100,000 a year

page: 8 -------------


$70,000 - $85,000 a year

page: 8 -------------


$64,800 - $73,200 a year

page: 8 -------------


$80,000 - $90,000 a year

page: 8 -------------


$19 - $26 an hour

page: 9 -------------


Up to $80,000 a year

page: 9 -------------


$90,000 - $100,000 a year

page: 9 -------------


$70,000 - $85,000 a year

page: 9 -------------


$64,800 - $73,200 a year

page: 9 -------------


$80,000 - $90,000 a year

page: 9 -------------


$19 - $26 an hour

page: 10 -------------


Up to $80,000 a year

page: 10 -------------


$90,000 - $100,000 a year

page: 10 -------------


$70,000 - $85,000 a year

page: 10 -------------


$64,800 - $73,200 a year

page: 10 -------------


$80,000 - $90,000 a year

page: 10 -------------


$19 - $26 an hour

In [13]:
company = soup.find_all ('span',class_='company')
company

[<span class="company">
 <a class="turnstileLink" data-tn-element="companyName" href="/cmp/Express-Employment-Professionals" onmousedown="this.href = appendParamsOnce(this.href, 'from=SERP&amp;campaignid=serp-linkcompanyname&amp;fromjk=c0a5122c52dfdb89&amp;jcid=39cba2423a5b76d1')" rel="noopener" target="_blank">
 Express Employment Professionals</a></span>,
 <span class="company">
 <a class="turnstileLink" data-tn-element="companyName" href="/cmp/Advantmed" onmousedown="this.href = appendParamsOnce(this.href, 'from=SERP&amp;campaignid=serp-linkcompanyname&amp;fromjk=e07c0ac47ced0143&amp;jcid=c15915d3940815ed')" rel="noopener" target="_blank">
 Advantmed</a></span>,
 <span class="company">
 <a class="turnstileLink" data-tn-element="companyName" href="/cmp/Acer-Service-Corporation" onmousedown="this.href = appendParamsOnce(this.href, 'from=SERP&amp;campaignid=serp-linkcompanyname&amp;fromjk=d47a2b69c7b43a40&amp;jcid=7f9826e7c7477ac9')" rel="noopener" target="_blank">
 Acer Service Corporation</a></span>,
 <span class="company">
 Ursus</span>,
 <span class="company">
 <a class="turnstileLink" data-tn-element="companyName" href="/cmp/Patra-Corp" onmousedown="this.href = appendParamsOnce(this.href, 'from=SERP&amp;campaignid=serp-linkcompanyname&amp;fromjk=5ffbd412f7c81170&amp;jcid=e096387274775791')" rel="noopener" target="_blank">
 Patra Corporation</a></span>,
 <span class="company">
 Standard Homeopathic Company / Hyland's</span>,
 <span class="company">
 <a class="turnstileLink" data-tn-element="companyName" href="/cmp/Heritage-Community-Credit-Union" onmousedown="this.href = appendParamsOnce(this.href, 'from=SERP&amp;campaignid=serp-linkcompanyname&amp;fromjk=a6a3a139f891dc96&amp;jcid=30bd84eb7063ccf1')" rel="noopener" target="_blank">
 Heritage Community Credit Union</a></span>,
 <span class="company">
 <a class="turnstileLink" data-tn-element="companyName" href="/cmp/Midland-Credit-Management" onmousedown="this.href = appendParamsOnce(this.href, 'from=SERP&amp;campaignid=serp-linkcompanyname&amp;fromjk=ebda34ad490cfb8f&amp;jcid=9ff926b033a6c08c')" rel="noopener" target="_blank">
 Midland Credit Management</a></span>,
 <span class="company">
 <a class="turnstileLink" data-tn-element="companyName" href="/cmp/E-&amp;-J-Gallo-Winery" onmousedown="this.href = appendParamsOnce(this.href, 'from=SERP&amp;campaignid=serp-linkcompanyname&amp;fromjk=8b95e3d5285db46a&amp;jcid=b244dd5afdd50c12')" rel="noopener" target="_blank">
 E.&amp;J. Gallo Winery</a></span>,
 <span class="company">
 <a class="turnstileLink" data-tn-element="companyName" href="/cmp/Amphenol" onmousedown="this.href = appendParamsOnce(this.href, 'from=SERP&amp;campaignid=serp-linkcompanyname&amp;fromjk=3fb21f8853e8b9da&amp;jcid=19f8534772728ff8')" rel="noopener" target="_blank">
 Amphenol Advanced Sensors</a></span>,
 <span class="company">
 Helm360</span>,
 <span class="company">
 <a class="turnstileLink" data-tn-element="companyName" href="/cmp/Course-Hero" onmousedown="this.href = appendParamsOnce(this.href, 'from=SERP&amp;campaignid=serp-linkcompanyname&amp;fromjk=bcc638c267d6d6ea&amp;jcid=85ffffaebf673194')" rel="noopener" target="_blank">
 Course Hero</a></span>,
 <span class="company">
 Biocept, Inc.</span>,
 <span class="company">
 <a class="turnstileLink" data-tn-element="companyName" href="/cmp/Pyramid" onmousedown="this.href = appendParamsOnce(this.href, 'from=SERP&amp;campaignid=serp-linkcompanyname&amp;fromjk=b3afaf6ef89ca4fa&amp;jcid=7b98e1432e30395f')" rel="noopener" target="_blank">
 Pyramid</a></span>,
 <span class="company">
 Sensor Tower</span>]

In [14]:
job_company = []


#loop through the returned result
for x in range(1, 11):
    company = soup.find_all("span", class_ = "company")
    for c in company:
        job_company.append(c.text)
        print('page:', x, '-------------')
        print(c.text)
        browser.find_by_xpath('/html/body/table[2]/tbody/tr/td/table/tbody/tr/td[1]/div[7]/div[1]/span[1]')

page: 1 -------------


Express Employment Professionals
page: 1 -------------


Advantmed
page: 1 -------------


Acer Service Corporation
page: 1 -------------

Ursus
page: 1 -------------


Patra Corporation
page: 1 -------------

Standard Homeopathic Company / Hyland's
page: 1 -------------


Heritage Community Credit Union
page: 1 -------------


Midland Credit Management
page: 1 -------------


E.&J. Gallo Winery
page: 1 -------------


Amphenol Advanced Sensors
page: 1 -------------

Helm360
page: 1 -------------


Course Hero
page: 1 -------------

Biocept, Inc.
page: 1 -------------


Pyramid
page: 1 -------------

Sensor Tower
page: 2 -------------


Express Employment Professionals
page: 2 -------------


Advantmed
page: 2 -------------


Acer Service Corporation
page: 2 -------------

Ursus
page: 2 -------------


Patra Corporation
page: 2 -------------

Standard Homeopathic Company / Hyland's
page: 2 -------------


Heritage Community Credit Union
page: 2 -------------


Midland Credit Management
page: 2 -------------


E.&J. Gallo Winery
page: 2 -------------


Amphenol Advanced Sensors
page: 2 -------------

Helm360
page: 2 -------------


Course Hero
page: 2 -------------

Biocept, Inc.
page: 2 -------------


Pyramid
page: 2 -------------

Sensor Tower
page: 3 -------------


Express Employment Professionals
page: 3 -------------


Advantmed
page: 3 -------------


Acer Service Corporation
page: 3 -------------

Ursus
page: 3 -------------


Patra Corporation
page: 3 -------------

Standard Homeopathic Company / Hyland's
page: 3 -------------


Heritage Community Credit Union
page: 3 -------------


Midland Credit Management
page: 3 -------------


E.&J. Gallo Winery
page: 3 -------------


Amphenol Advanced Sensors
page: 3 -------------

Helm360
page: 3 -------------


Course Hero
page: 3 -------------

Biocept, Inc.
page: 3 -------------


Pyramid
page: 3 -------------

Sensor Tower
page: 4 -------------


Express Employment Professionals
page: 4 -------------


Advantmed
page: 4 -------------


Acer Service Corporation
page: 4 -------------

Ursus
page: 4 -------------


Patra Corporation
page: 4 -------------

Standard Homeopathic Company / Hyland's
page: 4 -------------


Heritage Community Credit Union
page: 4 -------------


Midland Credit Management
page: 4 -------------


E.&J. Gallo Winery
page: 4 -------------


Amphenol Advanced Sensors
page: 4 -------------

Helm360
page: 4 -------------


Course Hero
page: 4 -------------

Biocept, Inc.
page: 4 -------------


Pyramid
page: 4 -------------

Sensor Tower
page: 5 -------------


Express Employment Professionals
page: 5 -------------


Advantmed
page: 5 -------------


Acer Service Corporation
page: 5 -------------

Ursus
page: 5 -------------


Patra Corporation
page: 5 -------------

Standard Homeopathic Company / Hyland's
page: 5 -------------


Heritage Community Credit Union
page: 5 -------------


Midland Credit Management
page: 5 -------------


E.&J. Gallo Winery
page: 5 -------------


Amphenol Advanced Sensors
page: 5 -------------

Helm360
page: 5 -------------


Course Hero
page: 5 -------------

Biocept, Inc.
page: 5 -------------


Pyramid
page: 5 -------------

Sensor Tower
page: 6 -------------


Express Employment Professionals
page: 6 -------------


Advantmed
page: 6 -------------


Acer Service Corporation
page: 6 -------------

Ursus
page: 6 -------------


Patra Corporation
page: 6 -------------

Standard Homeopathic Company / Hyland's
page: 6 -------------


Heritage Community Credit Union
page: 6 -------------


Midland Credit Management
page: 6 -------------


E.&J. Gallo Winery
page: 6 -------------


Amphenol Advanced Sensors
page: 6 -------------

Helm360
page: 6 -------------


Course Hero
page: 6 -------------

Biocept, Inc.
page: 6 -------------


Pyramid
page: 6 -------------

Sensor Tower
page: 7 -------------


Express Employment Professionals
page: 7 -------------


Advantmed
page: 7 -------------


Acer Service Corporation
page: 7 -------------

Ursus
page: 7 -------------


Patra Corporation
page: 7 -------------

Standard Homeopathic Company / Hyland's
page: 7 -------------


Heritage Community Credit Union
page: 7 -------------


Midland Credit Management
page: 7 -------------


E.&J. Gallo Winery
page: 7 -------------


Amphenol Advanced Sensors
page: 7 -------------

Helm360
page: 7 -------------


Course Hero
page: 7 -------------

Biocept, Inc.
page: 7 -------------


Pyramid
page: 7 -------------

Sensor Tower
page: 8 -------------


Express Employment Professionals
page: 8 -------------


Advantmed
page: 8 -------------


Acer Service Corporation
page: 8 -------------

Ursus
page: 8 -------------


Patra Corporation
page: 8 -------------

Standard Homeopathic Company / Hyland's
page: 8 -------------


Heritage Community Credit Union
page: 8 -------------


Midland Credit Management
page: 8 -------------


E.&J. Gallo Winery
page: 8 -------------


Amphenol Advanced Sensors
page: 8 -------------

Helm360
page: 8 -------------


Course Hero
page: 8 -------------

Biocept, Inc.
page: 8 -------------


Pyramid
page: 8 -------------

Sensor Tower
page: 9 -------------


Express Employment Professionals
page: 9 -------------


Advantmed
page: 9 -------------


Acer Service Corporation
page: 9 -------------

Ursus
page: 9 -------------


Patra Corporation
page: 9 -------------

Standard Homeopathic Company / Hyland's
page: 9 -------------


Heritage Community Credit Union
page: 9 -------------


Midland Credit Management
page: 9 -------------


E.&J. Gallo Winery
page: 9 -------------


Amphenol Advanced Sensors
page: 9 -------------

Helm360
page: 9 -------------


Course Hero
page: 9 -------------

Biocept, Inc.
page: 9 -------------


Pyramid
page: 9 -------------

Sensor Tower
page: 10 -------------


Express Employment Professionals
page: 10 -------------


Advantmed
page: 10 -------------


Acer Service Corporation
page: 10 -------------

Ursus
page: 10 -------------


Patra Corporation
page: 10 -------------

Standard Homeopathic Company / Hyland's
page: 10 -------------


Heritage Community Credit Union
page: 10 -------------


Midland Credit Management
page: 10 -------------


E.&J. Gallo Winery
page: 10 -------------


Amphenol Advanced Sensors
page: 10 -------------

Helm360
page: 10 -------------


Course Hero
page: 10 -------------

Biocept, Inc.
page: 10 -------------


Pyramid
page: 10 -------------

Sensor Tower

In [15]:
date = soup.find_all("span", class_ = "date")
date


################# ASK the TA <<<<<<<<<<<<<<<<< how to convert ?????

[<span class="date">Just posted</span>,
 <span class="date">14 days ago</span>,
 <span class="date">30+ days ago</span>,
 <span class="date">5 days ago</span>,
 <span class="date">5 days ago</span>,
 <span class="date">14 days ago</span>,
 <span class="date">5 days ago</span>,
 <span class="date">30+ days ago</span>,
 <span class="date">1 day ago</span>,
 <span class="date">1 day ago</span>,
 <span class="date">14 days ago</span>,
 <span class="date">Today</span>,
 <span class="date">Just posted</span>,
 <span class="date">15 days ago</span>,
 <span class="date">Today</span>]

In [16]:
job_date = []


#loop through the returned result
for x in range(1, 11):
    date = soup.find_all("span", class_ = "date")
    for d in date:
        job_date.append(d.text)
        print('page:', x, '-------------')
        print(d.text)
        browser.find_by_xpath('/html/body/table[2]/tbody/tr/td/table/tbody/tr/td[1]/div[7]/div[1]/span[1]')

page: 1 -------------
Just posted
page: 1 -------------
14 days ago
page: 1 -------------
30+ days ago
page: 1 -------------
5 days ago
page: 1 -------------
5 days ago
page: 1 -------------
14 days ago
page: 1 -------------
5 days ago
page: 1 -------------
30+ days ago
page: 1 -------------
1 day ago
page: 1 -------------
1 day ago
page: 1 -------------
14 days ago
page: 1 -------------
Today
page: 1 -------------
Just posted
page: 1 -------------
15 days ago
page: 1 -------------
Today
page: 2 -------------
Just posted
page: 2 -------------
14 days ago
page: 2 -------------
30+ days ago
page: 2 -------------
5 days ago
page: 2 -------------
5 days ago
page: 2 -------------
14 days ago
page: 2 -------------
5 days ago
page: 2 -------------
30+ days ago
page: 2 -------------
1 day ago
page: 2 -------------
1 day ago
page: 2 -------------
14 days ago
page: 2 -------------
Today
page: 2 -------------
Just posted
page: 2 -------------
15 days ago
page: 2 -------------
Today
page: 3 -------------
Just posted
page: 3 -------------
14 days ago
page: 3 -------------
30+ days ago
page: 3 -------------
5 days ago
page: 3 -------------
5 days ago
page: 3 -------------
14 days ago
page: 3 -------------
5 days ago
page: 3 -------------
30+ days ago
page: 3 -------------
1 day ago
page: 3 -------------
1 day ago
page: 3 -------------
14 days ago
page: 3 -------------
Today
page: 3 -------------
Just posted
page: 3 -------------
15 days ago
page: 3 -------------
Today
page: 4 -------------
Just posted
page: 4 -------------
14 days ago
page: 4 -------------
30+ days ago
page: 4 -------------
5 days ago
page: 4 -------------
5 days ago
page: 4 -------------
14 days ago
page: 4 -------------
5 days ago
page: 4 -------------
30+ days ago
page: 4 -------------
1 day ago
page: 4 -------------
1 day ago
page: 4 -------------
14 days ago
page: 4 -------------
Today
page: 4 -------------
Just posted
page: 4 -------------
15 days ago
page: 4 -------------
Today
page: 5 -------------
Just posted
page: 5 -------------
14 days ago
page: 5 -------------
30+ days ago
page: 5 -------------
5 days ago
page: 5 -------------
5 days ago
page: 5 -------------
14 days ago
page: 5 -------------
5 days ago
page: 5 -------------
30+ days ago
page: 5 -------------
1 day ago
page: 5 -------------
1 day ago
page: 5 -------------
14 days ago
page: 5 -------------
Today
page: 5 -------------
Just posted
page: 5 -------------
15 days ago
page: 5 -------------
Today
page: 6 -------------
Just posted
page: 6 -------------
14 days ago
page: 6 -------------
30+ days ago
page: 6 -------------
5 days ago
page: 6 -------------
5 days ago
page: 6 -------------
14 days ago
page: 6 -------------
5 days ago
page: 6 -------------
30+ days ago
page: 6 -------------
1 day ago
page: 6 -------------
1 day ago
page: 6 -------------
14 days ago
page: 6 -------------
Today
page: 6 -------------
Just posted
page: 6 -------------
15 days ago
page: 6 -------------
Today
page: 7 -------------
Just posted
page: 7 -------------
14 days ago
page: 7 -------------
30+ days ago
page: 7 -------------
5 days ago
page: 7 -------------
5 days ago
page: 7 -------------
14 days ago
page: 7 -------------
5 days ago
page: 7 -------------
30+ days ago
page: 7 -------------
1 day ago
page: 7 -------------
1 day ago
page: 7 -------------
14 days ago
page: 7 -------------
Today
page: 7 -------------
Just posted
page: 7 -------------
15 days ago
page: 7 -------------
Today
page: 8 -------------
Just posted
page: 8 -------------
14 days ago
page: 8 -------------
30+ days ago
page: 8 -------------
5 days ago
page: 8 -------------
5 days ago
page: 8 -------------
14 days ago
page: 8 -------------
5 days ago
page: 8 -------------
30+ days ago
page: 8 -------------
1 day ago
page: 8 -------------
1 day ago
page: 8 -------------
14 days ago
page: 8 -------------
Today
page: 8 -------------
Just posted
page: 8 -------------
15 days ago
page: 8 -------------
Today
page: 9 -------------
Just posted
page: 9 -------------
14 days ago
page: 9 -------------
30+ days ago
page: 9 -------------
5 days ago
page: 9 -------------
5 days ago
page: 9 -------------
14 days ago
page: 9 -------------
5 days ago
page: 9 -------------
30+ days ago
page: 9 -------------
1 day ago
page: 9 -------------
1 day ago
page: 9 -------------
14 days ago
page: 9 -------------
Today
page: 9 -------------
Just posted
page: 9 -------------
15 days ago
page: 9 -------------
Today
page: 10 -------------
Just posted
page: 10 -------------
14 days ago
page: 10 -------------
30+ days ago
page: 10 -------------
5 days ago
page: 10 -------------
5 days ago
page: 10 -------------
14 days ago
page: 10 -------------
5 days ago
page: 10 -------------
30+ days ago
page: 10 -------------
1 day ago
page: 10 -------------
1 day ago
page: 10 -------------
14 days ago
page: 10 -------------
Today
page: 10 -------------
Just posted
page: 10 -------------
15 days ago
page: 10 -------------
Today

In [19]:
#Use replace to print out a clean job title
clean_job_titles = []

#loop through result
for job in job_titles[1:]:
    clean_job_title = job.replace('\n', '')
    clean_job_titles.append(clean_job_title)

In [25]:
#Use replace to print out a clean job title
clean_salary = []

#loop through result
for ss in job_salary[1:]:
    clean_s= ss.replace('\n', '')
    clean_salary.append(clean_s)
print(clean_salary)

['$90,000 - $100,000 a year', '$70,000 - $85,000 a year', '$64,800 - $73,200 a year', '$80,000 - $90,000 a year', '$19 - $26 an hour', 'Up to $80,000 a year', '$90,000 - $100,000 a year', '$70,000 - $85,000 a year', '$64,800 - $73,200 a year', '$80,000 - $90,000 a year', '$19 - $26 an hour', 'Up to $80,000 a year', '$90,000 - $100,000 a year', '$70,000 - $85,000 a year', '$64,800 - $73,200 a year', '$80,000 - $90,000 a year', '$19 - $26 an hour', 'Up to $80,000 a year', '$90,000 - $100,000 a year', '$70,000 - $85,000 a year', '$64,800 - $73,200 a year', '$80,000 - $90,000 a year', '$19 - $26 an hour', 'Up to $80,000 a year', '$90,000 - $100,000 a year', '$70,000 - $85,000 a year', '$64,800 - $73,200 a year', '$80,000 - $90,000 a year', '$19 - $26 an hour', 'Up to $80,000 a year', '$90,000 - $100,000 a year', '$70,000 - $85,000 a year', '$64,800 - $73,200 a year', '$80,000 - $90,000 a year', '$19 - $26 an hour', 'Up to $80,000 a year', '$90,000 - $100,000 a year', '$70,000 - $85,000 a year', '$64,800 - $73,200 a year', '$80,000 - $90,000 a year', '$19 - $26 an hour', 'Up to $80,000 a year', '$90,000 - $100,000 a year', '$70,000 - $85,000 a year', '$64,800 - $73,200 a year', '$80,000 - $90,000 a year', '$19 - $26 an hour', 'Up to $80,000 a year', '$90,000 - $100,000 a year', '$70,000 - $85,000 a year', '$64,800 - $73,200 a year', '$80,000 - $90,000 a year', '$19 - $26 an hour', 'Up to $80,000 a year', '$90,000 - $100,000 a year', '$70,000 - $85,000 a year', '$64,800 - $73,200 a year', '$80,000 - $90,000 a year', '$19 - $26 an hour']

In [27]:
clean_location = []

#loop through result
for lo in job_locations[1:]:
    clean_l= lo.replace('\n', '')
    clean_location.append(clean_l)
print(clean_location)

['Sacramento, CA 95827', 'Modesto, CA 95354', 'Morgan Hill, CA', 'Poway, CA 92064', 'Redwood City, CA 94063 (Downtown area)', 'San Diego, CA 92121 (Sorrento Valley area)', 'Pleasanton, CA', 'San Francisco, CA', 'El Dorado Hills, CA 95762', 'Sacramento, CA 95827', 'Modesto, CA 95354', 'Morgan Hill, CA', 'Poway, CA 92064', 'Redwood City, CA 94063 (Downtown area)', 'San Diego, CA 92121 (Sorrento Valley area)', 'Pleasanton, CA', 'San Francisco, CA', 'El Dorado Hills, CA 95762', 'Sacramento, CA 95827', 'Modesto, CA 95354', 'Morgan Hill, CA', 'Poway, CA 92064', 'Redwood City, CA 94063 (Downtown area)', 'San Diego, CA 92121 (Sorrento Valley area)', 'Pleasanton, CA', 'San Francisco, CA', 'El Dorado Hills, CA 95762', 'Sacramento, CA 95827', 'Modesto, CA 95354', 'Morgan Hill, CA', 'Poway, CA 92064', 'Redwood City, CA 94063 (Downtown area)', 'San Diego, CA 92121 (Sorrento Valley area)', 'Pleasanton, CA', 'San Francisco, CA', 'El Dorado Hills, CA 95762', 'Sacramento, CA 95827', 'Modesto, CA 95354', 'Morgan Hill, CA', 'Poway, CA 92064', 'Redwood City, CA 94063 (Downtown area)', 'San Diego, CA 92121 (Sorrento Valley area)', 'Pleasanton, CA', 'San Francisco, CA', 'El Dorado Hills, CA 95762', 'Sacramento, CA 95827', 'Modesto, CA 95354', 'Morgan Hill, CA', 'Poway, CA 92064', 'Redwood City, CA 94063 (Downtown area)', 'San Diego, CA 92121 (Sorrento Valley area)', 'Pleasanton, CA', 'San Francisco, CA', 'El Dorado Hills, CA 95762', 'Sacramento, CA 95827', 'Modesto, CA 95354', 'Morgan Hill, CA', 'Poway, CA 92064', 'Redwood City, CA 94063 (Downtown area)', 'San Diego, CA 92121 (Sorrento Valley area)', 'Pleasanton, CA', 'San Francisco, CA', 'El Dorado Hills, CA 95762', 'Sacramento, CA 95827', 'Modesto, CA 95354', 'Morgan Hill, CA', 'Poway, CA 92064', 'Redwood City, CA 94063 (Downtown area)', 'San Diego, CA 92121 (Sorrento Valley area)', 'Pleasanton, CA', 'San Francisco, CA', 'El Dorado Hills, CA 95762', 'Sacramento, CA 95827', 'Modesto, CA 95354', 'Morgan Hill, CA', 'Poway, CA 92064', 'Redwood City, CA 94063 (Downtown area)', 'San Diego, CA 92121 (Sorrento Valley area)', 'Pleasanton, CA', 'San Francisco, CA', 'El Dorado Hills, CA 95762', 'Sacramento, CA 95827', 'Modesto, CA 95354', 'Morgan Hill, CA', 'Poway, CA 92064', 'Redwood City, CA 94063 (Downtown area)', 'San Diego, CA 92121 (Sorrento Valley area)', 'Pleasanton, CA', 'San Francisco, CA']

In [29]:
clean_company = []

#loop through result
for company in job_company[1:]:
    clean_com= company.replace('\n', '')
    clean_company.append(clean_com)
print(clean_company)

['Advantmed', 'Acer Service Corporation', 'Ursus', 'Patra Corporation', "Standard Homeopathic Company / Hyland's", 'Heritage Community Credit Union', 'Midland Credit Management', 'E.&J. Gallo Winery', 'Amphenol Advanced Sensors', 'Helm360', 'Course Hero', 'Biocept, Inc.', 'Pyramid', 'Sensor Tower', 'Express Employment Professionals', 'Advantmed', 'Acer Service Corporation', 'Ursus', 'Patra Corporation', "Standard Homeopathic Company / Hyland's", 'Heritage Community Credit Union', 'Midland Credit Management', 'E.&J. Gallo Winery', 'Amphenol Advanced Sensors', 'Helm360', 'Course Hero', 'Biocept, Inc.', 'Pyramid', 'Sensor Tower', 'Express Employment Professionals', 'Advantmed', 'Acer Service Corporation', 'Ursus', 'Patra Corporation', "Standard Homeopathic Company / Hyland's", 'Heritage Community Credit Union', 'Midland Credit Management', 'E.&J. Gallo Winery', 'Amphenol Advanced Sensors', 'Helm360', 'Course Hero', 'Biocept, Inc.', 'Pyramid', 'Sensor Tower', 'Express Employment Professionals', 'Advantmed', 'Acer Service Corporation', 'Ursus', 'Patra Corporation', "Standard Homeopathic Company / Hyland's", 'Heritage Community Credit Union', 'Midland Credit Management', 'E.&J. Gallo Winery', 'Amphenol Advanced Sensors', 'Helm360', 'Course Hero', 'Biocept, Inc.', 'Pyramid', 'Sensor Tower', 'Express Employment Professionals', 'Advantmed', 'Acer Service Corporation', 'Ursus', 'Patra Corporation', "Standard Homeopathic Company / Hyland's", 'Heritage Community Credit Union', 'Midland Credit Management', 'E.&J. Gallo Winery', 'Amphenol Advanced Sensors', 'Helm360', 'Course Hero', 'Biocept, Inc.', 'Pyramid', 'Sensor Tower', 'Express Employment Professionals', 'Advantmed', 'Acer Service Corporation', 'Ursus', 'Patra Corporation', "Standard Homeopathic Company / Hyland's", 'Heritage Community Credit Union', 'Midland Credit Management', 'E.&J. Gallo Winery', 'Amphenol Advanced Sensors', 'Helm360', 'Course Hero', 'Biocept, Inc.', 'Pyramid', 'Sensor Tower', 'Express Employment Professionals', 'Advantmed', 'Acer Service Corporation', 'Ursus', 'Patra Corporation', "Standard Homeopathic Company / Hyland's", 'Heritage Community Credit Union', 'Midland Credit Management', 'E.&J. Gallo Winery', 'Amphenol Advanced Sensors', 'Helm360', 'Course Hero', 'Biocept, Inc.', 'Pyramid', 'Sensor Tower', 'Express Employment Professionals', 'Advantmed', 'Acer Service Corporation', 'Ursus', 'Patra Corporation', "Standard Homeopathic Company / Hyland's", 'Heritage Community Credit Union', 'Midland Credit Management', 'E.&J. Gallo Winery', 'Amphenol Advanced Sensors', 'Helm360', 'Course Hero', 'Biocept, Inc.', 'Pyramid', 'Sensor Tower', 'Express Employment Professionals', 'Advantmed', 'Acer Service Corporation', 'Ursus', 'Patra Corporation', "Standard Homeopathic Company / Hyland's", 'Heritage Community Credit Union', 'Midland Credit Management', 'E.&J. Gallo Winery', 'Amphenol Advanced Sensors', 'Helm360', 'Course Hero', 'Biocept, Inc.', 'Pyramid', 'Sensor Tower', 'Express Employment Professionals', 'Advantmed', 'Acer Service Corporation', 'Ursus', 'Patra Corporation', "Standard Homeopathic Company / Hyland's", 'Heritage Community Credit Union', 'Midland Credit Management', 'E.&J. Gallo Winery', 'Amphenol Advanced Sensors', 'Helm360', 'Course Hero', 'Biocept, Inc.', 'Pyramid', 'Sensor Tower']

In [30]:
new_list = list(zip(clean_job_titles, job_locations,clean_salary,clean_company,job_date))
new_list

[('Business Systems Data Analystnew',
  'El Dorado Hills, CA 95762',
  '$90,000 - $100,000 a year',
  'Advantmed',
  'Just posted'),
 ('Senior Data Analyst (Healthcare and HEDIS experience)',
  'Sacramento, CA 95827',
  '$70,000 - $85,000 a year',
  'Acer Service Corporation',
  '14 days ago'),
 ('Data Analyst',
  'Modesto, CA 95354',
  '$64,800 - $73,200 a year',
  'Ursus',
  '30+ days ago'),
 ('Data Analyst - 017832new',
  'Morgan Hill, CA',
  '$80,000 - $90,000 a year',
  'Patra Corporation',
  '5 days ago'),
 ('Data Analystnew',
  'Poway, CA 92064',
  '$19 - $26 an hour',
  "Standard Homeopathic Company / Hyland's",
  '5 days ago'),
 ('Data Analyst',
  'Redwood City, CA 94063 (Downtown area)',
  'Up to $80,000 a year',
  'Heritage Community Credit Union',
  '14 days ago'),
 ('Marketing Specialist & Data Analystnew',
  'San Diego, CA 92121 (Sorrento Valley area)',
  '$90,000 - $100,000 a year',
  'Midland Credit Management',
  '5 days ago'),
 ('Data Analyst',
  'Pleasanton, CA',
  '$70,000 - $85,000 a year',
  'E.&J. Gallo Winery',
  '30+ days ago'),
 ('Sales Data Analystnew',
  'San Francisco, CA',
  '$64,800 - $73,200 a year',
  'Amphenol Advanced Sensors',
  '1 day ago'),
 ('Data Analystnew',
  'El Dorado Hills, CA 95762',
  '$80,000 - $90,000 a year',
  'Helm360',
  '1 day ago'),
 ('Junior Data Analyst',
  'Sacramento, CA 95827',
  '$19 - $26 an hour',
  'Course Hero',
  '14 days ago'),
 ('Data Analyst IInew',
  'Modesto, CA 95354',
  'Up to $80,000 a year',
  'Biocept, Inc.',
  'Today'),
 ('Data Analyst Temporarynew',
  'Morgan Hill, CA',
  '$90,000 - $100,000 a year',
  'Pyramid',
  'Just posted'),
 ('Jr. Data Analyst',
  'Poway, CA 92064',
  '$70,000 - $85,000 a year',
  'Sensor Tower',
  '15 days ago'),
 ('Data Operations Analystnew',
  'Redwood City, CA 94063 (Downtown area)',
  '$64,800 - $73,200 a year',
  'Express Employment Professionals',
  'Today'),
 ('Business Systems Data Analystnew',
  'San Diego, CA 92121 (Sorrento Valley area)',
  '$80,000 - $90,000 a year',
  'Advantmed',
  'Just posted'),
 ('Senior Data Analyst (Healthcare and HEDIS experience)',
  'Pleasanton, CA',
  '$19 - $26 an hour',
  'Acer Service Corporation',
  '14 days ago'),
 ('Data Analyst',
  'San Francisco, CA',
  'Up to $80,000 a year',
  'Ursus',
  '30+ days ago'),
 ('Data Analyst - 017832new',
  'El Dorado Hills, CA 95762',
  '$90,000 - $100,000 a year',
  'Patra Corporation',
  '5 days ago'),
 ('Data Analystnew',
  'Sacramento, CA 95827',
  '$70,000 - $85,000 a year',
  "Standard Homeopathic Company / Hyland's",
  '5 days ago'),
 ('Data Analyst',
  'Modesto, CA 95354',
  '$64,800 - $73,200 a year',
  'Heritage Community Credit Union',
  '14 days ago'),
 ('Marketing Specialist & Data Analystnew',
  'Morgan Hill, CA',
  '$80,000 - $90,000 a year',
  'Midland Credit Management',
  '5 days ago'),
 ('Data Analyst',
  'Poway, CA 92064',
  '$19 - $26 an hour',
  'E.&J. Gallo Winery',
  '30+ days ago'),
 ('Sales Data Analystnew',
  'Redwood City, CA 94063 (Downtown area)',
  'Up to $80,000 a year',
  'Amphenol Advanced Sensors',
  '1 day ago'),
 ('Data Analystnew',
  'San Diego, CA 92121 (Sorrento Valley area)',
  '$90,000 - $100,000 a year',
  'Helm360',
  '1 day ago'),
 ('Junior Data Analyst',
  'Pleasanton, CA',
  '$70,000 - $85,000 a year',
  'Course Hero',
  '14 days ago'),
 ('Data Analyst IInew',
  'San Francisco, CA',
  '$64,800 - $73,200 a year',
  'Biocept, Inc.',
  'Today'),
 ('Data Analyst Temporarynew',
  'El Dorado Hills, CA 95762',
  '$80,000 - $90,000 a year',
  'Pyramid',
  'Just posted'),
 ('Jr. Data Analyst',
  'Sacramento, CA 95827',
  '$19 - $26 an hour',
  'Sensor Tower',
  '15 days ago'),
 ('Data Operations Analystnew',
  'Modesto, CA 95354',
  'Up to $80,000 a year',
  'Express Employment Professionals',
  'Today'),
 ('Business Systems Data Analystnew',
  'Morgan Hill, CA',
  '$90,000 - $100,000 a year',
  'Advantmed',
  'Just posted'),
 ('Senior Data Analyst (Healthcare and HEDIS experience)',
  'Poway, CA 92064',
  '$70,000 - $85,000 a year',
  'Acer Service Corporation',
  '14 days ago'),
 ('Data Analyst',
  'Redwood City, CA 94063 (Downtown area)',
  '$64,800 - $73,200 a year',
  'Ursus',
  '30+ days ago'),
 ('Data Analyst - 017832new',
  'San Diego, CA 92121 (Sorrento Valley area)',
  '$80,000 - $90,000 a year',
  'Patra Corporation',
  '5 days ago'),
 ('Data Analystnew',
  'Pleasanton, CA',
  '$19 - $26 an hour',
  "Standard Homeopathic Company / Hyland's",
  '5 days ago'),
 ('Data Analyst',
  'San Francisco, CA',
  'Up to $80,000 a year',
  'Heritage Community Credit Union',
  '14 days ago'),
 ('Marketing Specialist & Data Analystnew',
  'El Dorado Hills, CA 95762',
  '$90,000 - $100,000 a year',
  'Midland Credit Management',
  '5 days ago'),
 ('Data Analyst',
  'Sacramento, CA 95827',
  '$70,000 - $85,000 a year',
  'E.&J. Gallo Winery',
  '30+ days ago'),
 ('Sales Data Analystnew',
  'Modesto, CA 95354',
  '$64,800 - $73,200 a year',
  'Amphenol Advanced Sensors',
  '1 day ago'),
 ('Data Analystnew',
  'Morgan Hill, CA',
  '$80,000 - $90,000 a year',
  'Helm360',
  '1 day ago'),
 ('Junior Data Analyst',
  'Poway, CA 92064',
  '$19 - $26 an hour',
  'Course Hero',
  '14 days ago'),
 ('Data Analyst IInew',
  'Redwood City, CA 94063 (Downtown area)',
  'Up to $80,000 a year',
  'Biocept, Inc.',
  'Today'),
 ('Data Analyst Temporarynew',
  'San Diego, CA 92121 (Sorrento Valley area)',
  '$90,000 - $100,000 a year',
  'Pyramid',
  'Just posted'),
 ('Jr. Data Analyst',
  'Pleasanton, CA',
  '$70,000 - $85,000 a year',
  'Sensor Tower',
  '15 days ago'),
 ('Data Operations Analystnew',
  'San Francisco, CA',
  '$64,800 - $73,200 a year',
  'Express Employment Professionals',
  'Today'),
 ('Business Systems Data Analystnew',
  'El Dorado Hills, CA 95762',
  '$80,000 - $90,000 a year',
  'Advantmed',
  'Just posted'),
 ('Senior Data Analyst (Healthcare and HEDIS experience)',
  'Sacramento, CA 95827',
  '$19 - $26 an hour',
  'Acer Service Corporation',
  '14 days ago'),
 ('Data Analyst',
  'Modesto, CA 95354',
  'Up to $80,000 a year',
  'Ursus',
  '30+ days ago'),
 ('Data Analyst - 017832new',
  'Morgan Hill, CA',
  '$90,000 - $100,000 a year',
  'Patra Corporation',
  '5 days ago'),
 ('Data Analystnew',
  'Poway, CA 92064',
  '$70,000 - $85,000 a year',
  "Standard Homeopathic Company / Hyland's",
  '5 days ago'),
 ('Data Analyst',
  'Redwood City, CA 94063 (Downtown area)',
  '$64,800 - $73,200 a year',
  'Heritage Community Credit Union',
  '14 days ago'),
 ('Marketing Specialist & Data Analystnew',
  'San Diego, CA 92121 (Sorrento Valley area)',
  '$80,000 - $90,000 a year',
  'Midland Credit Management',
  '5 days ago'),
 ('Data Analyst',
  'Pleasanton, CA',
  '$19 - $26 an hour',
  'E.&J. Gallo Winery',
  '30+ days ago'),
 ('Sales Data Analystnew',
  'San Francisco, CA',
  'Up to $80,000 a year',
  'Amphenol Advanced Sensors',
  '1 day ago'),
 ('Data Analystnew',
  'El Dorado Hills, CA 95762',
  '$90,000 - $100,000 a year',
  'Helm360',
  '1 day ago'),
 ('Junior Data Analyst',
  'Sacramento, CA 95827',
  '$70,000 - $85,000 a year',
  'Course Hero',
  '14 days ago'),
 ('Data Analyst IInew',
  'Modesto, CA 95354',
  '$64,800 - $73,200 a year',
  'Biocept, Inc.',
  'Today'),
 ('Data Analyst Temporarynew',
  'Morgan Hill, CA',
  '$80,000 - $90,000 a year',
  'Pyramid',
  'Just posted'),
 ('Jr. Data Analyst',
  'Poway, CA 92064',
  '$19 - $26 an hour',
  'Sensor Tower',
  '15 days ago')]

In [32]:
New_job_location_df = pd.DataFrame(new_list, columns=['job_Title', 'location','salary','company','posted_date'])
New_job_location_df

,job_Title,location,salary,company,posted_date
0,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Advantmed,Just posted
1,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago
2,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Ursus,30+ days ago
3,Data Analyst - 017832new,"Morgan Hill, CA","$80,000 - $90,000 a year",Patra Corporation,5 days ago
4,Data Analystnew,"Poway, CA 92064",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago
5,Data Analyst,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Heritage Community Credit Union,14 days ago
6,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Midland Credit Management,5 days ago
7,Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago
8,Sales Data Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago
9,Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Helm360,1 day ago
10,Junior Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Course Hero,14 days ago
11,Data Analyst IInew,"Modesto, CA 95354","Up to $80,000 a year","Biocept, Inc.",Today
12,Data Analyst Temporarynew,"Morgan Hill, CA","$90,000 - $100,000 a year",Pyramid,Just posted
13,Jr. Data Analyst,"Poway, CA 92064","$70,000 - $85,000 a year",Sensor Tower,15 days ago
14,Data Operations Analystnew,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Express Employment Professionals,Today
15,Business Systems Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Advantmed,Just posted
16,Senior Data Analyst (Healthcare and HEDIS expe...,"Pleasanton, CA",$19 - $26 an hour,Acer Service Corporation,14 days ago
17,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Ursus,30+ days ago
18,Data Analyst - 017832new,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Patra Corporation,5 days ago
19,Data Analystnew,"Sacramento, CA 95827","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago
20,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago
21,Marketing Specialist & Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Midland Credit Management,5 days ago
22,Data Analyst,"Poway, CA 92064",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago
23,Sales Data Analystnew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago
24,Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Helm360,1 day ago
25,Junior Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Course Hero,14 days ago
26,Data Analyst IInew,"San Francisco, CA","$64,800 - $73,200 a year","Biocept, Inc.",Today
27,Data Analyst Temporarynew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Pyramid,Just posted
28,Jr. Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Sensor Tower,15 days ago
29,Data Operations Analystnew,"Modesto, CA 95354","Up to $80,000 a year",Express Employment Professionals,Today
30,Business Systems Data Analystnew,"Morgan Hill, CA","$90,000 - $100,000 a year",Advantmed,Just posted
31,Senior Data Analyst (Healthcare and HEDIS expe...,"Poway, CA 92064","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago
32,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Ursus,30+ days ago
33,Data Analyst - 017832new,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Patra Corporation,5 days ago
34,Data Analystnew,"Pleasanton, CA",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago
35,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Heritage Community Credit Union,14 days ago
36,Marketing Specialist & Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Midland Credit Management,5 days ago
37,Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago
38,Sales Data Analystnew,"Modesto, CA 95354","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago
39,Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Helm360,1 day ago
40,Junior Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Course Hero,14 days ago
41,Data Analyst IInew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year","Biocept, Inc.",Today
42,Data Analyst Temporarynew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Pyramid,Just posted
43,Jr. Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Sensor Tower,15 days ago
44,Data Operations Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Express Employment Professionals,Today
45,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Advantmed,Just posted
46,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827",$19 - $26 an hour,Acer Service Corporation,14 days ago
47,Data Analyst,"Modesto, CA 95354","Up to $80,000 a year",Ursus,30+ days ago
48,Data Analyst - 017832new,"Morgan Hill, CA","$90,000 - $100,000 a year",Patra Corporation,5 days ago
49,Data Analystnew,"Poway, CA 92064","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago
50,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago
51,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Midland Credit Management,5 days ago
52,Data Analyst,"Pleasanton, CA",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago
53,Sales Data Analystnew,"San Francisco, CA","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago
54,Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Helm360,1 day ago
55,Junior Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",Course Hero,14 days ago
56,Data Analyst IInew,"Modesto, CA 95354","$64,800 - $73,200 a year","Biocept, Inc.",Today
57,Data Analyst Temporarynew,"Morgan Hill, CA","$80,000 - $90,000 a year",Pyramid,Just posted
58,Jr. Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Sensor Tower,15 days ago

In [35]:
New_job_location_df['city'] = New_job_location_df['location'].str.split(',').str[0]
New_job_location_df

,job_Title,location,salary,company,posted_date,city
0,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Advantmed,Just posted,El Dorado Hills
1,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Sacramento
2,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Ursus,30+ days ago,Modesto
3,Data Analyst - 017832new,"Morgan Hill, CA","$80,000 - $90,000 a year",Patra Corporation,5 days ago,Morgan Hill
4,Data Analystnew,"Poway, CA 92064",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Poway
5,Data Analyst,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,Redwood City
6,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,San Diego
7,Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Pleasanton
8,Sales Data Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,San Francisco
9,Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Helm360,1 day ago,El Dorado Hills
10,Junior Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Course Hero,14 days ago,Sacramento
11,Data Analyst IInew,"Modesto, CA 95354","Up to $80,000 a year","Biocept, Inc.",Today,Modesto
12,Data Analyst Temporarynew,"Morgan Hill, CA","$90,000 - $100,000 a year",Pyramid,Just posted,Morgan Hill
13,Jr. Data Analyst,"Poway, CA 92064","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Poway
14,Data Operations Analystnew,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Express Employment Professionals,Today,Redwood City
15,Business Systems Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Advantmed,Just posted,San Diego
16,Senior Data Analyst (Healthcare and HEDIS expe...,"Pleasanton, CA",$19 - $26 an hour,Acer Service Corporation,14 days ago,Pleasanton
17,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Ursus,30+ days ago,San Francisco
18,Data Analyst - 017832new,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Patra Corporation,5 days ago,El Dorado Hills
19,Data Analystnew,"Sacramento, CA 95827","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Sacramento
20,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Modesto
21,Marketing Specialist & Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,Morgan Hill
22,Data Analyst,"Poway, CA 92064",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Poway
23,Sales Data Analystnew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,Redwood City
24,Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Helm360,1 day ago,San Diego
25,Junior Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Course Hero,14 days ago,Pleasanton
26,Data Analyst IInew,"San Francisco, CA","$64,800 - $73,200 a year","Biocept, Inc.",Today,San Francisco
27,Data Analyst Temporarynew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Pyramid,Just posted,El Dorado Hills
28,Jr. Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Sensor Tower,15 days ago,Sacramento
29,Data Operations Analystnew,"Modesto, CA 95354","Up to $80,000 a year",Express Employment Professionals,Today,Modesto
30,Business Systems Data Analystnew,"Morgan Hill, CA","$90,000 - $100,000 a year",Advantmed,Just posted,Morgan Hill
31,Senior Data Analyst (Healthcare and HEDIS expe...,"Poway, CA 92064","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Poway
32,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Ursus,30+ days ago,Redwood City
33,Data Analyst - 017832new,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Patra Corporation,5 days ago,San Diego
34,Data Analystnew,"Pleasanton, CA",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Pleasanton
35,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,San Francisco
36,Marketing Specialist & Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,El Dorado Hills
37,Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Sacramento
38,Sales Data Analystnew,"Modesto, CA 95354","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,Modesto
39,Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Helm360,1 day ago,Morgan Hill
40,Junior Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Course Hero,14 days ago,Poway
41,Data Analyst IInew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year","Biocept, Inc.",Today,Redwood City
42,Data Analyst Temporarynew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Pyramid,Just posted,San Diego
43,Jr. Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Pleasanton
44,Data Operations Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Express Employment Professionals,Today,San Francisco
45,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Advantmed,Just posted,El Dorado Hills
46,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827",$19 - $26 an hour,Acer Service Corporation,14 days ago,Sacramento
47,Data Analyst,"Modesto, CA 95354","Up to $80,000 a year",Ursus,30+ days ago,Modesto
48,Data Analyst - 017832new,"Morgan Hill, CA","$90,000 - $100,000 a year",Patra Corporation,5 days ago,Morgan Hill
49,Data Analystnew,"Poway, CA 92064","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Poway
50,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Redwood City
51,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,San Diego
52,Data Analyst,"Pleasanton, CA",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Pleasanton
53,Sales Data Analystnew,"San Francisco, CA","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,San Francisco
54,Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Helm360,1 day ago,El Dorado Hills
55,Junior Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",Course Hero,14 days ago,Sacramento
56,Data Analyst IInew,"Modesto, CA 95354","$64,800 - $73,200 a year","Biocept, Inc.",Today,Modesto
57,Data Analyst Temporarynew,"Morgan Hill, CA","$80,000 - $90,000 a year",Pyramid,Just posted,Morgan Hill
58,Jr. Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Sensor Tower,15 days ago,Poway

In [39]:
New_job_location_df['temp'] = New_job_location_df['location'].str.split(',').str[1]
New_job_location_df

,job_Title,location,salary,company,posted_date,city,zip,temp
0,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762
1,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827
2,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354
3,Data Analyst - 017832new,"Morgan Hill, CA","$80,000 - $90,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA
4,Data Analystnew,"Poway, CA 92064",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064
5,Data Analyst,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area)
6,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area)
7,Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA
8,Sales Data Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA
9,Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762
10,Junior Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Course Hero,14 days ago,Sacramento,CA 95827,CA 95827
11,Data Analyst IInew,"Modesto, CA 95354","Up to $80,000 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354
12,Data Analyst Temporarynew,"Morgan Hill, CA","$90,000 - $100,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA
13,Jr. Data Analyst,"Poway, CA 92064","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Poway,CA 92064,CA 92064
14,Data Operations Analystnew,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Express Employment Professionals,Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area)
15,Business Systems Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Advantmed,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area)
16,Senior Data Analyst (Healthcare and HEDIS expe...,"Pleasanton, CA",$19 - $26 an hour,Acer Service Corporation,14 days ago,Pleasanton,CA,CA
17,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Ursus,30+ days ago,San Francisco,CA,CA
18,Data Analyst - 017832new,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Patra Corporation,5 days ago,El Dorado Hills,CA 95762,CA 95762
19,Data Analystnew,"Sacramento, CA 95827","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Sacramento,CA 95827,CA 95827
20,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Modesto,CA 95354,CA 95354
21,Marketing Specialist & Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,Morgan Hill,CA,CA
22,Data Analyst,"Poway, CA 92064",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Poway,CA 92064,CA 92064
23,Sales Data Analystnew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area)
24,Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Helm360,1 day ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area)
25,Junior Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Course Hero,14 days ago,Pleasanton,CA,CA
26,Data Analyst IInew,"San Francisco, CA","$64,800 - $73,200 a year","Biocept, Inc.",Today,San Francisco,CA,CA
27,Data Analyst Temporarynew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Pyramid,Just posted,El Dorado Hills,CA 95762,CA 95762
28,Jr. Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Sensor Tower,15 days ago,Sacramento,CA 95827,CA 95827
29,Data Operations Analystnew,"Modesto, CA 95354","Up to $80,000 a year",Express Employment Professionals,Today,Modesto,CA 95354,CA 95354
30,Business Systems Data Analystnew,"Morgan Hill, CA","$90,000 - $100,000 a year",Advantmed,Just posted,Morgan Hill,CA,CA
31,Senior Data Analyst (Healthcare and HEDIS expe...,"Poway, CA 92064","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Poway,CA 92064,CA 92064
32,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Ursus,30+ days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area)
33,Data Analyst - 017832new,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Patra Corporation,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area)
34,Data Analystnew,"Pleasanton, CA",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Pleasanton,CA,CA
35,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,San Francisco,CA,CA
36,Marketing Specialist & Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,El Dorado Hills,CA 95762,CA 95762
37,Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Sacramento,CA 95827,CA 95827
38,Sales Data Analystnew,"Modesto, CA 95354","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,Modesto,CA 95354,CA 95354
39,Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Helm360,1 day ago,Morgan Hill,CA,CA
40,Junior Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Course Hero,14 days ago,Poway,CA 92064,CA 92064
41,Data Analyst IInew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year","Biocept, Inc.",Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area)
42,Data Analyst Temporarynew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Pyramid,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area)
43,Jr. Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Pleasanton,CA,CA
44,Data Operations Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Express Employment Professionals,Today,San Francisco,CA,CA
45,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762
46,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827",$19 - $26 an hour,Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827
47,Data Analyst,"Modesto, CA 95354","Up to $80,000 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354
48,Data Analyst - 017832new,"Morgan Hill, CA","$90,000 - $100,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA
49,Data Analystnew,"Poway, CA 92064","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064
50,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area)
51,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area)
52,Data Analyst,"Pleasanton, CA",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA
53,Sales Data Analystnew,"San Francisco, CA","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA
54,Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762
55,Junior Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",Course Hero,14 days ago,Sacramento,CA 95827,CA 95827
56,Data Analyst IInew,"Modesto, CA 95354","$64,800 - $73,200 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354
57,Data Analyst Temporarynew,"Morgan Hill, CA","$80,000 - $90,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA
58,Jr. Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Sensor Tower,15 days ago,Poway,CA 92064,CA 92064

In [44]:
New_job_location_df['state'] = New_job_location_df['temp'].str.split().str[0]
New_job_location_df

,job_Title,location,salary,company,posted_date,city,zip,temp,state
0,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA
1,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA
2,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA
3,Data Analyst - 017832new,"Morgan Hill, CA","$80,000 - $90,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA
4,Data Analystnew,"Poway, CA 92064",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA
5,Data Analyst,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA
6,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA
7,Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA,CA
8,Sales Data Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA,CA
9,Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762,CA
10,Junior Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Course Hero,14 days ago,Sacramento,CA 95827,CA 95827,CA
11,Data Analyst IInew,"Modesto, CA 95354","Up to $80,000 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354,CA
12,Data Analyst Temporarynew,"Morgan Hill, CA","$90,000 - $100,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA,CA
13,Jr. Data Analyst,"Poway, CA 92064","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Poway,CA 92064,CA 92064,CA
14,Data Operations Analystnew,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Express Employment Professionals,Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA
15,Business Systems Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Advantmed,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA
16,Senior Data Analyst (Healthcare and HEDIS expe...,"Pleasanton, CA",$19 - $26 an hour,Acer Service Corporation,14 days ago,Pleasanton,CA,CA,CA
17,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Ursus,30+ days ago,San Francisco,CA,CA,CA
18,Data Analyst - 017832new,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Patra Corporation,5 days ago,El Dorado Hills,CA 95762,CA 95762,CA
19,Data Analystnew,"Sacramento, CA 95827","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Sacramento,CA 95827,CA 95827,CA
20,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Modesto,CA 95354,CA 95354,CA
21,Marketing Specialist & Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,Morgan Hill,CA,CA,CA
22,Data Analyst,"Poway, CA 92064",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Poway,CA 92064,CA 92064,CA
23,Sales Data Analystnew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA
24,Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Helm360,1 day ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA
25,Junior Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Course Hero,14 days ago,Pleasanton,CA,CA,CA
26,Data Analyst IInew,"San Francisco, CA","$64,800 - $73,200 a year","Biocept, Inc.",Today,San Francisco,CA,CA,CA
27,Data Analyst Temporarynew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Pyramid,Just posted,El Dorado Hills,CA 95762,CA 95762,CA
28,Jr. Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Sensor Tower,15 days ago,Sacramento,CA 95827,CA 95827,CA
29,Data Operations Analystnew,"Modesto, CA 95354","Up to $80,000 a year",Express Employment Professionals,Today,Modesto,CA 95354,CA 95354,CA
30,Business Systems Data Analystnew,"Morgan Hill, CA","$90,000 - $100,000 a year",Advantmed,Just posted,Morgan Hill,CA,CA,CA
31,Senior Data Analyst (Healthcare and HEDIS expe...,"Poway, CA 92064","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Poway,CA 92064,CA 92064,CA
32,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Ursus,30+ days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA
33,Data Analyst - 017832new,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Patra Corporation,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA
34,Data Analystnew,"Pleasanton, CA",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Pleasanton,CA,CA,CA
35,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,San Francisco,CA,CA,CA
36,Marketing Specialist & Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,El Dorado Hills,CA 95762,CA 95762,CA
37,Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Sacramento,CA 95827,CA 95827,CA
38,Sales Data Analystnew,"Modesto, CA 95354","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,Modesto,CA 95354,CA 95354,CA
39,Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Helm360,1 day ago,Morgan Hill,CA,CA,CA
40,Junior Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Course Hero,14 days ago,Poway,CA 92064,CA 92064,CA
41,Data Analyst IInew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year","Biocept, Inc.",Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA
42,Data Analyst Temporarynew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Pyramid,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA
43,Jr. Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Pleasanton,CA,CA,CA
44,Data Operations Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Express Employment Professionals,Today,San Francisco,CA,CA,CA
45,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA
46,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827",$19 - $26 an hour,Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA
47,Data Analyst,"Modesto, CA 95354","Up to $80,000 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA
48,Data Analyst - 017832new,"Morgan Hill, CA","$90,000 - $100,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA
49,Data Analystnew,"Poway, CA 92064","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA
50,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA
51,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA
52,Data Analyst,"Pleasanton, CA",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA,CA
53,Sales Data Analystnew,"San Francisco, CA","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA,CA
54,Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762,CA
55,Junior Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",Course Hero,14 days ago,Sacramento,CA 95827,CA 95827,CA
56,Data Analyst IInew,"Modesto, CA 95354","$64,800 - $73,200 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354,CA
57,Data Analyst Temporarynew,"Morgan Hill, CA","$80,000 - $90,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA,CA
58,Jr. Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Sensor Tower,15 days ago,Poway,CA 92064,CA 92064,CA

In [45]:
New_job_location_df['zip_code'] = New_job_location_df['temp'].str.split().str[1]
New_job_location_df

,job_Title,location,salary,company,posted_date,city,zip,temp,state,zip_code
0,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762
1,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827
2,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA,95354
3,Data Analyst - 017832new,"Morgan Hill, CA","$80,000 - $90,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA,NaN
4,Data Analystnew,"Poway, CA 92064",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA,92064
5,Data Analyst,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063
6,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121
7,Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA,CA,NaN
8,Sales Data Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA,CA,NaN
9,Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762,CA,95762
10,Junior Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Course Hero,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827
11,Data Analyst IInew,"Modesto, CA 95354","Up to $80,000 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354,CA,95354
12,Data Analyst Temporarynew,"Morgan Hill, CA","$90,000 - $100,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA,CA,NaN
13,Jr. Data Analyst,"Poway, CA 92064","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Poway,CA 92064,CA 92064,CA,92064
14,Data Operations Analystnew,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Express Employment Professionals,Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063
15,Business Systems Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Advantmed,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121
16,Senior Data Analyst (Healthcare and HEDIS expe...,"Pleasanton, CA",$19 - $26 an hour,Acer Service Corporation,14 days ago,Pleasanton,CA,CA,CA,NaN
17,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Ursus,30+ days ago,San Francisco,CA,CA,CA,NaN
18,Data Analyst - 017832new,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Patra Corporation,5 days ago,El Dorado Hills,CA 95762,CA 95762,CA,95762
19,Data Analystnew,"Sacramento, CA 95827","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Sacramento,CA 95827,CA 95827,CA,95827
20,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Modesto,CA 95354,CA 95354,CA,95354
21,Marketing Specialist & Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,Morgan Hill,CA,CA,CA,NaN
22,Data Analyst,"Poway, CA 92064",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Poway,CA 92064,CA 92064,CA,92064
23,Sales Data Analystnew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063
24,Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Helm360,1 day ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121
25,Junior Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Course Hero,14 days ago,Pleasanton,CA,CA,CA,NaN
26,Data Analyst IInew,"San Francisco, CA","$64,800 - $73,200 a year","Biocept, Inc.",Today,San Francisco,CA,CA,CA,NaN
27,Data Analyst Temporarynew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Pyramid,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762
28,Jr. Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Sensor Tower,15 days ago,Sacramento,CA 95827,CA 95827,CA,95827
29,Data Operations Analystnew,"Modesto, CA 95354","Up to $80,000 a year",Express Employment Professionals,Today,Modesto,CA 95354,CA 95354,CA,95354
30,Business Systems Data Analystnew,"Morgan Hill, CA","$90,000 - $100,000 a year",Advantmed,Just posted,Morgan Hill,CA,CA,CA,NaN
31,Senior Data Analyst (Healthcare and HEDIS expe...,"Poway, CA 92064","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Poway,CA 92064,CA 92064,CA,92064
32,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Ursus,30+ days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063
33,Data Analyst - 017832new,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Patra Corporation,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121
34,Data Analystnew,"Pleasanton, CA",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Pleasanton,CA,CA,CA,NaN
35,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,San Francisco,CA,CA,CA,NaN
36,Marketing Specialist & Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,El Dorado Hills,CA 95762,CA 95762,CA,95762
37,Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Sacramento,CA 95827,CA 95827,CA,95827
38,Sales Data Analystnew,"Modesto, CA 95354","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,Modesto,CA 95354,CA 95354,CA,95354
39,Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Helm360,1 day ago,Morgan Hill,CA,CA,CA,NaN
40,Junior Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Course Hero,14 days ago,Poway,CA 92064,CA 92064,CA,92064
41,Data Analyst IInew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year","Biocept, Inc.",Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063
42,Data Analyst Temporarynew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Pyramid,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121
43,Jr. Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Pleasanton,CA,CA,CA,NaN
44,Data Operations Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Express Employment Professionals,Today,San Francisco,CA,CA,CA,NaN
45,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762
46,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827",$19 - $26 an hour,Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827
47,Data Analyst,"Modesto, CA 95354","Up to $80,000 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA,95354
48,Data Analyst - 017832new,"Morgan Hill, CA","$90,000 - $100,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA,NaN
49,Data Analystnew,"Poway, CA 92064","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA,92064
50,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063
51,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121
52,Data Analyst,"Pleasanton, CA",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA,CA,NaN
53,Sales Data Analystnew,"San Francisco, CA","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA,CA,NaN
54,Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762,CA,95762
55,Junior Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",Course Hero,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827
56,Data Analyst IInew,"Modesto, CA 95354","$64,800 - $73,200 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354,CA,95354
57,Data Analyst Temporarynew,"Morgan Hill, CA","$80,000 - $90,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA,CA,NaN
58,Jr. Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Sensor Tower,15 days ago,Poway,CA 92064,CA 92064,CA,92064

In [47]:
New_job_location_df['job_type'] = 'Data Analyst'
New_job_location_df

,job_Title,location,salary,company,posted_date,city,zip,temp,state,zip_code,job_type
0,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst
1,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst
2,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst
3,Data Analyst - 017832new,"Morgan Hill, CA","$80,000 - $90,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst
4,Data Analystnew,"Poway, CA 92064",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst
5,Data Analyst,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst
6,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst
7,Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst
8,Sales Data Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA,CA,NaN,Data Analyst
9,Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst
10,Junior Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Course Hero,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst
11,Data Analyst IInew,"Modesto, CA 95354","Up to $80,000 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst
12,Data Analyst Temporarynew,"Morgan Hill, CA","$90,000 - $100,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst
13,Jr. Data Analyst,"Poway, CA 92064","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst
14,Data Operations Analystnew,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Express Employment Professionals,Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst
15,Business Systems Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Advantmed,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst
16,Senior Data Analyst (Healthcare and HEDIS expe...,"Pleasanton, CA",$19 - $26 an hour,Acer Service Corporation,14 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst
17,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Ursus,30+ days ago,San Francisco,CA,CA,CA,NaN,Data Analyst
18,Data Analyst - 017832new,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Patra Corporation,5 days ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst
19,Data Analystnew,"Sacramento, CA 95827","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst
20,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst
21,Marketing Specialist & Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst
22,Data Analyst,"Poway, CA 92064",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst
23,Sales Data Analystnew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst
24,Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Helm360,1 day ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst
25,Junior Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Course Hero,14 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst
26,Data Analyst IInew,"San Francisco, CA","$64,800 - $73,200 a year","Biocept, Inc.",Today,San Francisco,CA,CA,CA,NaN,Data Analyst
27,Data Analyst Temporarynew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Pyramid,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst
28,Jr. Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Sensor Tower,15 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst
29,Data Operations Analystnew,"Modesto, CA 95354","Up to $80,000 a year",Express Employment Professionals,Today,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst
30,Business Systems Data Analystnew,"Morgan Hill, CA","$90,000 - $100,000 a year",Advantmed,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst
31,Senior Data Analyst (Healthcare and HEDIS expe...,"Poway, CA 92064","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst
32,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Ursus,30+ days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst
33,Data Analyst - 017832new,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Patra Corporation,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst
34,Data Analystnew,"Pleasanton, CA",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst
35,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,San Francisco,CA,CA,CA,NaN,Data Analyst
36,Marketing Specialist & Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst
37,Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst
38,Sales Data Analystnew,"Modesto, CA 95354","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst
39,Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Helm360,1 day ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst
40,Junior Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Course Hero,14 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst
41,Data Analyst IInew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year","Biocept, Inc.",Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst
42,Data Analyst Temporarynew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Pyramid,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst
43,Jr. Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst
44,Data Operations Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Express Employment Professionals,Today,San Francisco,CA,CA,CA,NaN,Data Analyst
45,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst
46,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827",$19 - $26 an hour,Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst
47,Data Analyst,"Modesto, CA 95354","Up to $80,000 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst
48,Data Analyst - 017832new,"Morgan Hill, CA","$90,000 - $100,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst
49,Data Analystnew,"Poway, CA 92064","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst
50,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst
51,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst
52,Data Analyst,"Pleasanton, CA",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst
53,Sales Data Analystnew,"San Francisco, CA","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA,CA,NaN,Data Analyst
54,Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst
55,Junior Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",Course Hero,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst
56,Data Analyst IInew,"Modesto, CA 95354","$64,800 - $73,200 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst
57,Data Analyst Temporarynew,"Morgan Hill, CA","$80,000 - $90,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst
58,Jr. Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Sensor Tower,15 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst

In [50]:
New_job_location_df['low_range'] = New_job_location_df['salary'].str.split('-').str[0]
New_job_location_df['high'] = New_job_location_df['salary'].str.split('-').str[1]
New_job_location_df

,job_Title,location,salary,company,posted_date,city,zip,temp,state,zip_code,job_type,low_range,high_range,high
0,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$90,000","$100,000 a year","$100,000 a year"
1,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,"$70,000","$85,000 a year","$85,000 a year"
2,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"$64,800","$73,200 a year","$73,200 a year"
3,Data Analyst - 017832new,"Morgan Hill, CA","$80,000 - $90,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year"
4,Data Analystnew,"Poway, CA 92064",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,$19,$26 an hour,$26 an hour
5,Data Analyst,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"Up to $80,000 a year",NaN,NaN
6,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$90,000","$100,000 a year","$100,000 a year"
7,Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,"$70,000","$85,000 a year","$85,000 a year"
8,Sales Data Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"$64,800","$73,200 a year","$73,200 a year"
9,Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$80,000","$90,000 a year","$90,000 a year"
10,Junior Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Course Hero,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,$19,$26 an hour,$26 an hour
11,Data Analyst IInew,"Modesto, CA 95354","Up to $80,000 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"Up to $80,000 a year",NaN,NaN
12,Data Analyst Temporarynew,"Morgan Hill, CA","$90,000 - $100,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$90,000","$100,000 a year","$100,000 a year"
13,Jr. Data Analyst,"Poway, CA 92064","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,"$70,000","$85,000 a year","$85,000 a year"
14,Data Operations Analystnew,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Express Employment Professionals,Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"$64,800","$73,200 a year","$73,200 a year"
15,Business Systems Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Advantmed,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$80,000","$90,000 a year","$90,000 a year"
16,Senior Data Analyst (Healthcare and HEDIS expe...,"Pleasanton, CA",$19 - $26 an hour,Acer Service Corporation,14 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,$19,$26 an hour,$26 an hour
17,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Ursus,30+ days ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN,NaN
18,Data Analyst - 017832new,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Patra Corporation,5 days ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$90,000","$100,000 a year","$100,000 a year"
19,Data Analystnew,"Sacramento, CA 95827","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,"$70,000","$85,000 a year","$85,000 a year"
20,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"$64,800","$73,200 a year","$73,200 a year"
21,Marketing Specialist & Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year"
22,Data Analyst,"Poway, CA 92064",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,$19,$26 an hour,$26 an hour
23,Sales Data Analystnew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"Up to $80,000 a year",NaN,NaN
24,Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Helm360,1 day ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$90,000","$100,000 a year","$100,000 a year"
25,Junior Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Course Hero,14 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,"$70,000","$85,000 a year","$85,000 a year"
26,Data Analyst IInew,"San Francisco, CA","$64,800 - $73,200 a year","Biocept, Inc.",Today,San Francisco,CA,CA,CA,NaN,Data Analyst,"$64,800","$73,200 a year","$73,200 a year"
27,Data Analyst Temporarynew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Pyramid,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$80,000","$90,000 a year","$90,000 a year"
28,Jr. Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Sensor Tower,15 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,$19,$26 an hour,$26 an hour
29,Data Operations Analystnew,"Modesto, CA 95354","Up to $80,000 a year",Express Employment Professionals,Today,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"Up to $80,000 a year",NaN,NaN
30,Business Systems Data Analystnew,"Morgan Hill, CA","$90,000 - $100,000 a year",Advantmed,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$90,000","$100,000 a year","$100,000 a year"
31,Senior Data Analyst (Healthcare and HEDIS expe...,"Poway, CA 92064","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,"$70,000","$85,000 a year","$85,000 a year"
32,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Ursus,30+ days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"$64,800","$73,200 a year","$73,200 a year"
33,Data Analyst - 017832new,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Patra Corporation,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$80,000","$90,000 a year","$90,000 a year"
34,Data Analystnew,"Pleasanton, CA",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,$19,$26 an hour,$26 an hour
35,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN,NaN
36,Marketing Specialist & Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$90,000","$100,000 a year","$100,000 a year"
37,Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,"$70,000","$85,000 a year","$85,000 a year"
38,Sales Data Analystnew,"Modesto, CA 95354","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"$64,800","$73,200 a year","$73,200 a year"
39,Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Helm360,1 day ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year"
40,Junior Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Course Hero,14 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,$19,$26 an hour,$26 an hour
41,Data Analyst IInew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year","Biocept, Inc.",Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"Up to $80,000 a year",NaN,NaN
42,Data Analyst Temporarynew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Pyramid,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$90,000","$100,000 a year","$100,000 a year"
43,Jr. Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,"$70,000","$85,000 a year","$85,000 a year"
44,Data Operations Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Express Employment Professionals,Today,San Francisco,CA,CA,CA,NaN,Data Analyst,"$64,800","$73,200 a year","$73,200 a year"
45,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$80,000","$90,000 a year","$90,000 a year"
46,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827",$19 - $26 an hour,Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,$19,$26 an hour,$26 an hour
47,Data Analyst,"Modesto, CA 95354","Up to $80,000 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"Up to $80,000 a year",NaN,NaN
48,Data Analyst - 017832new,"Morgan Hill, CA","$90,000 - $100,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$90,000","$100,000 a year","$100,000 a year"
49,Data Analystnew,"Poway, CA 92064","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,"$70,000","$85,000 a year","$85,000 a year"
50,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"$64,800","$73,200 a year","$73,200 a year"
51,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$80,000","$90,000 a year","$90,000 a year"
52,Data Analyst,"Pleasanton, CA",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,$19,$26 an hour,$26 an hour
53,Sales Data Analystnew,"San Francisco, CA","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN,NaN
54,Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$90,000","$100,000 a year","$100,000 a year"
55,Junior Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",Course Hero,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,"$70,000","$85,000 a year","$85,000 a year"
56,Data Analyst IInew,"Modesto, CA 95354","$64,800 - $73,200 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"$64,800","$73,200 a year","$73,200 a year"
57,Data Analyst Temporarynew,"Morgan Hill, CA","$80,000 - $90,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year"
58,Jr. Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Sensor Tower,15 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,$19,$26 an hour,$26 an hour

In [51]:
New_job_location_df['High_range'] = New_job_location_df['high'].str.split().str[0]
New_job_location_df

,job_Title,location,salary,company,posted_date,city,zip,temp,state,zip_code,job_type,low_range,high_range,high,High_range
0,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000"
1,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000"
2,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200"
3,Data Analyst - 017832new,"Morgan Hill, CA","$80,000 - $90,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000"
4,Data Analystnew,"Poway, CA 92064",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,$19,$26 an hour,$26 an hour,$26
5,Data Analyst,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN
6,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000"
7,Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000"
8,Sales Data Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200"
9,Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000"
10,Junior Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Course Hero,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,$19,$26 an hour,$26 an hour,$26
11,Data Analyst IInew,"Modesto, CA 95354","Up to $80,000 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN
12,Data Analyst Temporarynew,"Morgan Hill, CA","$90,000 - $100,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000"
13,Jr. Data Analyst,"Poway, CA 92064","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000"
14,Data Operations Analystnew,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Express Employment Professionals,Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200"
15,Business Systems Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Advantmed,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000"
16,Senior Data Analyst (Healthcare and HEDIS expe...,"Pleasanton, CA",$19 - $26 an hour,Acer Service Corporation,14 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,$19,$26 an hour,$26 an hour,$26
17,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Ursus,30+ days ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN
18,Data Analyst - 017832new,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Patra Corporation,5 days ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000"
19,Data Analystnew,"Sacramento, CA 95827","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000"
20,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200"
21,Marketing Specialist & Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000"
22,Data Analyst,"Poway, CA 92064",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,$19,$26 an hour,$26 an hour,$26
23,Sales Data Analystnew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN
24,Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Helm360,1 day ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000"
25,Junior Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Course Hero,14 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000"
26,Data Analyst IInew,"San Francisco, CA","$64,800 - $73,200 a year","Biocept, Inc.",Today,San Francisco,CA,CA,CA,NaN,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200"
27,Data Analyst Temporarynew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Pyramid,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000"
28,Jr. Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Sensor Tower,15 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,$19,$26 an hour,$26 an hour,$26
29,Data Operations Analystnew,"Modesto, CA 95354","Up to $80,000 a year",Express Employment Professionals,Today,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN
30,Business Systems Data Analystnew,"Morgan Hill, CA","$90,000 - $100,000 a year",Advantmed,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000"
31,Senior Data Analyst (Healthcare and HEDIS expe...,"Poway, CA 92064","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000"
32,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Ursus,30+ days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200"
33,Data Analyst - 017832new,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Patra Corporation,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000"
34,Data Analystnew,"Pleasanton, CA",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,$19,$26 an hour,$26 an hour,$26
35,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN
36,Marketing Specialist & Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000"
37,Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000"
38,Sales Data Analystnew,"Modesto, CA 95354","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200"
39,Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Helm360,1 day ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000"
40,Junior Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Course Hero,14 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,$19,$26 an hour,$26 an hour,$26
41,Data Analyst IInew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year","Biocept, Inc.",Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN
42,Data Analyst Temporarynew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Pyramid,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000"
43,Jr. Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000"
44,Data Operations Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Express Employment Professionals,Today,San Francisco,CA,CA,CA,NaN,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200"
45,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000"
46,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827",$19 - $26 an hour,Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,$19,$26 an hour,$26 an hour,$26
47,Data Analyst,"Modesto, CA 95354","Up to $80,000 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN
48,Data Analyst - 017832new,"Morgan Hill, CA","$90,000 - $100,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000"
49,Data Analystnew,"Poway, CA 92064","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000"
50,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200"
51,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000"
52,Data Analyst,"Pleasanton, CA",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,$19,$26 an hour,$26 an hour,$26
53,Sales Data Analystnew,"San Francisco, CA","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN
54,Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000"
55,Junior Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",Course Hero,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000"
56,Data Analyst IInew,"Modesto, CA 95354","$64,800 - $73,200 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200"
57,Data Analyst Temporarynew,"Morgan Hill, CA","$80,000 - $90,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000"
58,Jr. Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Sensor Tower,15 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,$19,$26 an hour,$26 an hour,$26

In [55]:
New_job_location_df['01'] = New_job_location_df['posted_date'].str.split().str[0]
New_job_location_df['02'] = New_job_location_df['posted_date'].str.split().str[1]
New_job_location_df['03'] = New_job_location_df['posted_date'].str.split().str[2]
New_job_location_df

,job_Title,location,salary,company,posted_date,city,zip,temp,state,zip_code,job_type,low_range,high_range,high,High_range,01,02,03
0,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",Just,posted,NaN
1,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",14,days,ago
2,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",30+,days,ago
3,Data Analyst - 017832new,"Morgan Hill, CA","$80,000 - $90,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",5,days,ago
4,Data Analystnew,"Poway, CA 92064",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,$19,$26 an hour,$26 an hour,$26,5,days,ago
5,Data Analyst,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,14,days,ago
6,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",5,days,ago
7,Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",30+,days,ago
8,Sales Data Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",1,day,ago
9,Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",1,day,ago
10,Junior Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Course Hero,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,$19,$26 an hour,$26 an hour,$26,14,days,ago
11,Data Analyst IInew,"Modesto, CA 95354","Up to $80,000 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,Today,NaN,NaN
12,Data Analyst Temporarynew,"Morgan Hill, CA","$90,000 - $100,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",Just,posted,NaN
13,Jr. Data Analyst,"Poway, CA 92064","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",15,days,ago
14,Data Operations Analystnew,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Express Employment Professionals,Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",Today,NaN,NaN
15,Business Systems Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Advantmed,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",Just,posted,NaN
16,Senior Data Analyst (Healthcare and HEDIS expe...,"Pleasanton, CA",$19 - $26 an hour,Acer Service Corporation,14 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,$19,$26 an hour,$26 an hour,$26,14,days,ago
17,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Ursus,30+ days ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,30+,days,ago
18,Data Analyst - 017832new,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Patra Corporation,5 days ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",5,days,ago
19,Data Analystnew,"Sacramento, CA 95827","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",5,days,ago
20,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",14,days,ago
21,Marketing Specialist & Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",5,days,ago
22,Data Analyst,"Poway, CA 92064",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,$19,$26 an hour,$26 an hour,$26,30+,days,ago
23,Sales Data Analystnew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,1,day,ago
24,Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Helm360,1 day ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",1,day,ago
25,Junior Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Course Hero,14 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",14,days,ago
26,Data Analyst IInew,"San Francisco, CA","$64,800 - $73,200 a year","Biocept, Inc.",Today,San Francisco,CA,CA,CA,NaN,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",Today,NaN,NaN
27,Data Analyst Temporarynew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Pyramid,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",Just,posted,NaN
28,Jr. Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Sensor Tower,15 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,$19,$26 an hour,$26 an hour,$26,15,days,ago
29,Data Operations Analystnew,"Modesto, CA 95354","Up to $80,000 a year",Express Employment Professionals,Today,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,Today,NaN,NaN
30,Business Systems Data Analystnew,"Morgan Hill, CA","$90,000 - $100,000 a year",Advantmed,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",Just,posted,NaN
31,Senior Data Analyst (Healthcare and HEDIS expe...,"Poway, CA 92064","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",14,days,ago
32,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Ursus,30+ days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",30+,days,ago
33,Data Analyst - 017832new,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Patra Corporation,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",5,days,ago
34,Data Analystnew,"Pleasanton, CA",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,$19,$26 an hour,$26 an hour,$26,5,days,ago
35,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,14,days,ago
36,Marketing Specialist & Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",5,days,ago
37,Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",30+,days,ago
38,Sales Data Analystnew,"Modesto, CA 95354","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",1,day,ago
39,Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Helm360,1 day ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",1,day,ago
40,Junior Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Course Hero,14 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,$19,$26 an hour,$26 an hour,$26,14,days,ago
41,Data Analyst IInew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year","Biocept, Inc.",Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,Today,NaN,NaN
42,Data Analyst Temporarynew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Pyramid,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",Just,posted,NaN
43,Jr. Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",15,days,ago
44,Data Operations Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Express Employment Professionals,Today,San Francisco,CA,CA,CA,NaN,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",Today,NaN,NaN
45,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",Just,posted,NaN
46,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827",$19 - $26 an hour,Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,$19,$26 an hour,$26 an hour,$26,14,days,ago
47,Data Analyst,"Modesto, CA 95354","Up to $80,000 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,30+,days,ago
48,Data Analyst - 017832new,"Morgan Hill, CA","$90,000 - $100,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",5,days,ago
49,Data Analystnew,"Poway, CA 92064","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",5,days,ago
50,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",14,days,ago
51,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",5,days,ago
52,Data Analyst,"Pleasanton, CA",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,$19,$26 an hour,$26 an hour,$26,30+,days,ago
53,Sales Data Analystnew,"San Francisco, CA","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,1,day,ago
54,Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762,CA,95762,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",1,day,ago
55,Junior Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",Course Hero,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",14,days,ago
56,Data Analyst IInew,"Modesto, CA 95354","$64,800 - $73,200 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354,CA,95354,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",Today,NaN,NaN
57,Data Analyst Temporarynew,"Morgan Hill, CA","$80,000 - $90,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",Just,posted,NaN
58,Jr. Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Sensor Tower,15 days ago,Poway,CA 92064,CA 92064,CA,92064,Data Analyst,$19,$26 an hour,$26 an hour,$26,15,days,ago

In [62]:
New_job_location_df.to_csv('job_new.csv',index=False)

In [59]:
today = dt.datetime.now()
today

datetime.datetime(2020, 9, 16, 18, 41, 13, 83119)

In [61]:
date = New_job_location_df['01']

In [52]:
list(New_job_location_df)

['job_Title',
 'location',
 'salary',
 'company',
 'posted_date',
 'city',
 'zip',
 'temp',
 'state',
 'zip_code',
 'job_type',
 'low_range',
 'high_range',
 'high',
 'High_range']

In [53]:
newdf = New_job_location_df[['job_Title','company','location','posted_date','city','state','zip_code','job_type','low_range','High_range']].copy()
newdf

,job_Title,company,location,posted_date,city,state,zip_code,job_type,low_range,High_range
0,Business Systems Data Analystnew,Advantmed,"El Dorado Hills, CA 95762",Just posted,El Dorado Hills,CA,95762,Data Analyst,"$90,000","$100,000"
1,Senior Data Analyst (Healthcare and HEDIS expe...,Acer Service Corporation,"Sacramento, CA 95827",14 days ago,Sacramento,CA,95827,Data Analyst,"$70,000","$85,000"
2,Data Analyst,Ursus,"Modesto, CA 95354",30+ days ago,Modesto,CA,95354,Data Analyst,"$64,800","$73,200"
3,Data Analyst - 017832new,Patra Corporation,"Morgan Hill, CA",5 days ago,Morgan Hill,CA,NaN,Data Analyst,"$80,000","$90,000"
4,Data Analystnew,Standard Homeopathic Company / Hyland's,"Poway, CA 92064",5 days ago,Poway,CA,92064,Data Analyst,$19,$26
5,Data Analyst,Heritage Community Credit Union,"Redwood City, CA 94063 (Downtown area)",14 days ago,Redwood City,CA,94063,Data Analyst,"Up to $80,000 a year",NaN
6,Marketing Specialist & Data Analystnew,Midland Credit Management,"San Diego, CA 92121 (Sorrento Valley area)",5 days ago,San Diego,CA,92121,Data Analyst,"$90,000","$100,000"
7,Data Analyst,E.&J. Gallo Winery,"Pleasanton, CA",30+ days ago,Pleasanton,CA,NaN,Data Analyst,"$70,000","$85,000"
8,Sales Data Analystnew,Amphenol Advanced Sensors,"San Francisco, CA",1 day ago,San Francisco,CA,NaN,Data Analyst,"$64,800","$73,200"
9,Data Analystnew,Helm360,"El Dorado Hills, CA 95762",1 day ago,El Dorado Hills,CA,95762,Data Analyst,"$80,000","$90,000"
10,Junior Data Analyst,Course Hero,"Sacramento, CA 95827",14 days ago,Sacramento,CA,95827,Data Analyst,$19,$26
11,Data Analyst IInew,"Biocept, Inc.","Modesto, CA 95354",Today,Modesto,CA,95354,Data Analyst,"Up to $80,000 a year",NaN
12,Data Analyst Temporarynew,Pyramid,"Morgan Hill, CA",Just posted,Morgan Hill,CA,NaN,Data Analyst,"$90,000","$100,000"
13,Jr. Data Analyst,Sensor Tower,"Poway, CA 92064",15 days ago,Poway,CA,92064,Data Analyst,"$70,000","$85,000"
14,Data Operations Analystnew,Express Employment Professionals,"Redwood City, CA 94063 (Downtown area)",Today,Redwood City,CA,94063,Data Analyst,"$64,800","$73,200"
15,Business Systems Data Analystnew,Advantmed,"San Diego, CA 92121 (Sorrento Valley area)",Just posted,San Diego,CA,92121,Data Analyst,"$80,000","$90,000"
16,Senior Data Analyst (Healthcare and HEDIS expe...,Acer Service Corporation,"Pleasanton, CA",14 days ago,Pleasanton,CA,NaN,Data Analyst,$19,$26
17,Data Analyst,Ursus,"San Francisco, CA",30+ days ago,San Francisco,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN
18,Data Analyst - 017832new,Patra Corporation,"El Dorado Hills, CA 95762",5 days ago,El Dorado Hills,CA,95762,Data Analyst,"$90,000","$100,000"
19,Data Analystnew,Standard Homeopathic Company / Hyland's,"Sacramento, CA 95827",5 days ago,Sacramento,CA,95827,Data Analyst,"$70,000","$85,000"
20,Data Analyst,Heritage Community Credit Union,"Modesto, CA 95354",14 days ago,Modesto,CA,95354,Data Analyst,"$64,800","$73,200"
21,Marketing Specialist & Data Analystnew,Midland Credit Management,"Morgan Hill, CA",5 days ago,Morgan Hill,CA,NaN,Data Analyst,"$80,000","$90,000"
22,Data Analyst,E.&J. Gallo Winery,"Poway, CA 92064",30+ days ago,Poway,CA,92064,Data Analyst,$19,$26
23,Sales Data Analystnew,Amphenol Advanced Sensors,"Redwood City, CA 94063 (Downtown area)",1 day ago,Redwood City,CA,94063,Data Analyst,"Up to $80,000 a year",NaN
24,Data Analystnew,Helm360,"San Diego, CA 92121 (Sorrento Valley area)",1 day ago,San Diego,CA,92121,Data Analyst,"$90,000","$100,000"
25,Junior Data Analyst,Course Hero,"Pleasanton, CA",14 days ago,Pleasanton,CA,NaN,Data Analyst,"$70,000","$85,000"
26,Data Analyst IInew,"Biocept, Inc.","San Francisco, CA",Today,San Francisco,CA,NaN,Data Analyst,"$64,800","$73,200"
27,Data Analyst Temporarynew,Pyramid,"El Dorado Hills, CA 95762",Just posted,El Dorado Hills,CA,95762,Data Analyst,"$80,000","$90,000"
28,Jr. Data Analyst,Sensor Tower,"Sacramento, CA 95827",15 days ago,Sacramento,CA,95827,Data Analyst,$19,$26
29,Data Operations Analystnew,Express Employment Professionals,"Modesto, CA 95354",Today,Modesto,CA,95354,Data Analyst,"Up to $80,000 a year",NaN
30,Business Systems Data Analystnew,Advantmed,"Morgan Hill, CA",Just posted,Morgan Hill,CA,NaN,Data Analyst,"$90,000","$100,000"
31,Senior Data Analyst (Healthcare and HEDIS expe...,Acer Service Corporation,"Poway, CA 92064",14 days ago,Poway,CA,92064,Data Analyst,"$70,000","$85,000"
32,Data Analyst,Ursus,"Redwood City, CA 94063 (Downtown area)",30+ days ago,Redwood City,CA,94063,Data Analyst,"$64,800","$73,200"
33,Data Analyst - 017832new,Patra Corporation,"San Diego, CA 92121 (Sorrento Valley area)",5 days ago,San Diego,CA,92121,Data Analyst,"$80,000","$90,000"
34,Data Analystnew,Standard Homeopathic Company / Hyland's,"Pleasanton, CA",5 days ago,Pleasanton,CA,NaN,Data Analyst,$19,$26
35,Data Analyst,Heritage Community Credit Union,"San Francisco, CA",14 days ago,San Francisco,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN
36,Marketing Specialist & Data Analystnew,Midland Credit Management,"El Dorado Hills, CA 95762",5 days ago,El Dorado Hills,CA,95762,Data Analyst,"$90,000","$100,000"
37,Data Analyst,E.&J. Gallo Winery,"Sacramento, CA 95827",30+ days ago,Sacramento,CA,95827,Data Analyst,"$70,000","$85,000"
38,Sales Data Analystnew,Amphenol Advanced Sensors,"Modesto, CA 95354",1 day ago,Modesto,CA,95354,Data Analyst,"$64,800","$73,200"
39,Data Analystnew,Helm360,"Morgan Hill, CA",1 day ago,Morgan Hill,CA,NaN,Data Analyst,"$80,000","$90,000"
40,Junior Data Analyst,Course Hero,"Poway, CA 92064",14 days ago,Poway,CA,92064,Data Analyst,$19,$26
41,Data Analyst IInew,"Biocept, Inc.","Redwood City, CA 94063 (Downtown area)",Today,Redwood City,CA,94063,Data Analyst,"Up to $80,000 a year",NaN
42,Data Analyst Temporarynew,Pyramid,"San Diego, CA 92121 (Sorrento Valley area)",Just posted,San Diego,CA,92121,Data Analyst,"$90,000","$100,000"
43,Jr. Data Analyst,Sensor Tower,"Pleasanton, CA",15 days ago,Pleasanton,CA,NaN,Data Analyst,"$70,000","$85,000"
44,Data Operations Analystnew,Express Employment Professionals,"San Francisco, CA",Today,San Francisco,CA,NaN,Data Analyst,"$64,800","$73,200"
45,Business Systems Data Analystnew,Advantmed,"El Dorado Hills, CA 95762",Just posted,El Dorado Hills,CA,95762,Data Analyst,"$80,000","$90,000"
46,Senior Data Analyst (Healthcare and HEDIS expe...,Acer Service Corporation,"Sacramento, CA 95827",14 days ago,Sacramento,CA,95827,Data Analyst,$19,$26
47,Data Analyst,Ursus,"Modesto, CA 95354",30+ days ago,Modesto,CA,95354,Data Analyst,"Up to $80,000 a year",NaN
48,Data Analyst - 017832new,Patra Corporation,"Morgan Hill, CA",5 days ago,Morgan Hill,CA,NaN,Data Analyst,"$90,000","$100,000"
49,Data Analystnew,Standard Homeopathic Company / Hyland's,"Poway, CA 92064",5 days ago,Poway,CA,92064,Data Analyst,"$70,000","$85,000"
50,Data Analyst,Heritage Community Credit Union,"Redwood City, CA 94063 (Downtown area)",14 days ago,Redwood City,CA,94063,Data Analyst,"$64,800","$73,200"
51,Marketing Specialist & Data Analystnew,Midland Credit Management,"San Diego, CA 92121 (Sorrento Valley area)",5 days ago,San Diego,CA,92121,Data Analyst,"$80,000","$90,000"
52,Data Analyst,E.&J. Gallo Winery,"Pleasanton, CA",30+ days ago,Pleasanton,CA,NaN,Data Analyst,$19,$26
53,Sales Data Analystnew,Amphenol Advanced Sensors,"San Francisco, CA",1 day ago,San Francisco,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN
54,Data Analystnew,Helm360,"El Dorado Hills, CA 95762",1 day ago,El Dorado Hills,CA,95762,Data Analyst,"$90,000","$100,000"
55,Junior Data Analyst,Course Hero,"Sacramento, CA 95827",14 days ago,Sacramento,CA,95827,Data Analyst,"$70,000","$85,000"
56,Data Analyst IInew,"Biocept, Inc.","Modesto, CA 95354",Today,Modesto,CA,95354,Data Analyst,"$64,800","$73,200"
57,Data Analyst Temporarynew,Pyramid,"Morgan Hill, CA",Just posted,Morgan Hill,CA,NaN,Data Analyst,"$80,000","$90,000"
58,Jr. Data Analyst,Sensor Tower,"Poway, CA 92064",15 days ago,Poway,CA,92064,Data Analyst,$19,$26

In [64]:
file_one= "job_new_2.csv"

job_convert = pd.read_csv(file_one)
job_convert.head()

,job_Title,location,salary,company,posted_date,city,zip,temp,state,zip_code,job_type,low_range,high_range,high,High_range,formatted_date
0,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762.0,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",2020/9/16
1,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827.0,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",2020/9/2
2,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA,95354.0,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",2020/8/16
3,Data Analyst - 017832new,"Morgan Hill, CA","$80,000 - $90,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",2020/9/11
4,Data Analystnew,"Poway, CA 92064",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA,92064.0,Data Analyst,$19,$26 an hour,$26 an hour,$26,2020/9/11

In [69]:
job_convert['Zip_code'] = job_convert['zip_code'].astype(str).str.split('.').str[0]
#dfdate= usdata['Date'].astype(str).str.split('/',expand=True)
#dfdate.columns = ['month','date','year']
job_convert

,job_Title,location,salary,company,posted_date,city,zip,temp,state,zip_code,job_type,low_range,high_range,high,High_range,formatted_date,Zip_code
0,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762.0,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",2020/9/16,95762
1,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827.0,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",2020/9/2,95827
2,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA,95354.0,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",2020/8/16,95354
3,Data Analyst - 017832new,"Morgan Hill, CA","$80,000 - $90,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",2020/9/11,nan
4,Data Analystnew,"Poway, CA 92064",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA,92064.0,Data Analyst,$19,$26 an hour,$26 an hour,$26,2020/9/11,92064
5,Data Analyst,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063.0,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,2020/9/2,94063
6,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121.0,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",2020/9/11,92121
7,Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",2020/8/16,nan
8,Sales Data Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",2020/9/15,nan
9,Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762,CA,95762.0,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",2020/9/15,95762
10,Junior Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Course Hero,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827.0,Data Analyst,$19,$26 an hour,$26 an hour,$26,2020/9/2,95827
11,Data Analyst IInew,"Modesto, CA 95354","Up to $80,000 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354,CA,95354.0,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,2020/9/16,95354
12,Data Analyst Temporarynew,"Morgan Hill, CA","$90,000 - $100,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",2020/9/16,nan
13,Jr. Data Analyst,"Poway, CA 92064","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Poway,CA 92064,CA 92064,CA,92064.0,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",2020/9/1,92064
14,Data Operations Analystnew,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Express Employment Professionals,Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063.0,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",2020/9/16,94063
15,Business Systems Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Advantmed,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121.0,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",2020/9/16,92121
16,Senior Data Analyst (Healthcare and HEDIS expe...,"Pleasanton, CA",$19 - $26 an hour,Acer Service Corporation,14 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,$19,$26 an hour,$26 an hour,$26,2020/9/2,nan
17,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Ursus,30+ days ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,2020/8/16,nan
18,Data Analyst - 017832new,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Patra Corporation,5 days ago,El Dorado Hills,CA 95762,CA 95762,CA,95762.0,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",2020/9/11,95762
19,Data Analystnew,"Sacramento, CA 95827","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Sacramento,CA 95827,CA 95827,CA,95827.0,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",2020/9/11,95827
20,Data Analyst,"Modesto, CA 95354","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Modesto,CA 95354,CA 95354,CA,95354.0,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",2020/9/2,95354
21,Marketing Specialist & Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",2020/9/11,nan
22,Data Analyst,"Poway, CA 92064",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Poway,CA 92064,CA 92064,CA,92064.0,Data Analyst,$19,$26 an hour,$26 an hour,$26,2020/8/16,92064
23,Sales Data Analystnew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063.0,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,2020/9/15,94063
24,Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Helm360,1 day ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121.0,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",2020/9/15,92121
25,Junior Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Course Hero,14 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",2020/9/2,nan
26,Data Analyst IInew,"San Francisco, CA","$64,800 - $73,200 a year","Biocept, Inc.",Today,San Francisco,CA,CA,CA,NaN,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",2020/9/16,nan
27,Data Analyst Temporarynew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Pyramid,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762.0,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",2020/9/16,95762
28,Jr. Data Analyst,"Sacramento, CA 95827",$19 - $26 an hour,Sensor Tower,15 days ago,Sacramento,CA 95827,CA 95827,CA,95827.0,Data Analyst,$19,$26 an hour,$26 an hour,$26,2020/9/1,95827
29,Data Operations Analystnew,"Modesto, CA 95354","Up to $80,000 a year",Express Employment Professionals,Today,Modesto,CA 95354,CA 95354,CA,95354.0,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,2020/9/16,95354
30,Business Systems Data Analystnew,"Morgan Hill, CA","$90,000 - $100,000 a year",Advantmed,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",2020/9/16,nan
31,Senior Data Analyst (Healthcare and HEDIS expe...,"Poway, CA 92064","$70,000 - $85,000 a year",Acer Service Corporation,14 days ago,Poway,CA 92064,CA 92064,CA,92064.0,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",2020/9/2,92064
32,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Ursus,30+ days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063.0,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",2020/8/16,94063
33,Data Analyst - 017832new,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Patra Corporation,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121.0,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",2020/9/11,92121
34,Data Analystnew,"Pleasanton, CA",$19 - $26 an hour,Standard Homeopathic Company / Hyland's,5 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,$19,$26 an hour,$26 an hour,$26,2020/9/11,nan
35,Data Analyst,"San Francisco, CA","Up to $80,000 a year",Heritage Community Credit Union,14 days ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,2020/9/2,nan
36,Marketing Specialist & Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Midland Credit Management,5 days ago,El Dorado Hills,CA 95762,CA 95762,CA,95762.0,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",2020/9/11,95762
37,Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",E.&J. Gallo Winery,30+ days ago,Sacramento,CA 95827,CA 95827,CA,95827.0,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",2020/8/16,95827
38,Sales Data Analystnew,"Modesto, CA 95354","$64,800 - $73,200 a year",Amphenol Advanced Sensors,1 day ago,Modesto,CA 95354,CA 95354,CA,95354.0,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",2020/9/15,95354
39,Data Analystnew,"Morgan Hill, CA","$80,000 - $90,000 a year",Helm360,1 day ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",2020/9/15,nan
40,Junior Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Course Hero,14 days ago,Poway,CA 92064,CA 92064,CA,92064.0,Data Analyst,$19,$26 an hour,$26 an hour,$26,2020/9/2,92064
41,Data Analyst IInew,"Redwood City, CA 94063 (Downtown area)","Up to $80,000 a year","Biocept, Inc.",Today,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063.0,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,2020/9/16,94063
42,Data Analyst Temporarynew,"San Diego, CA 92121 (Sorrento Valley area)","$90,000 - $100,000 a year",Pyramid,Just posted,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121.0,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",2020/9/16,92121
43,Jr. Data Analyst,"Pleasanton, CA","$70,000 - $85,000 a year",Sensor Tower,15 days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",2020/9/1,nan
44,Data Operations Analystnew,"San Francisco, CA","$64,800 - $73,200 a year",Express Employment Professionals,Today,San Francisco,CA,CA,CA,NaN,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",2020/9/16,nan
45,Business Systems Data Analystnew,"El Dorado Hills, CA 95762","$80,000 - $90,000 a year",Advantmed,Just posted,El Dorado Hills,CA 95762,CA 95762,CA,95762.0,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",2020/9/16,95762
46,Senior Data Analyst (Healthcare and HEDIS expe...,"Sacramento, CA 95827",$19 - $26 an hour,Acer Service Corporation,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827.0,Data Analyst,$19,$26 an hour,$26 an hour,$26,2020/9/2,95827
47,Data Analyst,"Modesto, CA 95354","Up to $80,000 a year",Ursus,30+ days ago,Modesto,CA 95354,CA 95354,CA,95354.0,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,2020/8/16,95354
48,Data Analyst - 017832new,"Morgan Hill, CA","$90,000 - $100,000 a year",Patra Corporation,5 days ago,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",2020/9/11,nan
49,Data Analystnew,"Poway, CA 92064","$70,000 - $85,000 a year",Standard Homeopathic Company / Hyland's,5 days ago,Poway,CA 92064,CA 92064,CA,92064.0,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",2020/9/11,92064
50,Data Analyst,"Redwood City, CA 94063 (Downtown area)","$64,800 - $73,200 a year",Heritage Community Credit Union,14 days ago,Redwood City,CA 94063 (Downtown area),CA 94063 (Downtown area),CA,94063.0,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",2020/9/2,94063
51,Marketing Specialist & Data Analystnew,"San Diego, CA 92121 (Sorrento Valley area)","$80,000 - $90,000 a year",Midland Credit Management,5 days ago,San Diego,CA 92121 (Sorrento Valley area),CA 92121 (Sorrento Valley area),CA,92121.0,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",2020/9/11,92121
52,Data Analyst,"Pleasanton, CA",$19 - $26 an hour,E.&J. Gallo Winery,30+ days ago,Pleasanton,CA,CA,CA,NaN,Data Analyst,$19,$26 an hour,$26 an hour,$26,2020/8/16,nan
53,Sales Data Analystnew,"San Francisco, CA","Up to $80,000 a year",Amphenol Advanced Sensors,1 day ago,San Francisco,CA,CA,CA,NaN,Data Analyst,"Up to $80,000 a year",NaN,NaN,NaN,2020/9/15,nan
54,Data Analystnew,"El Dorado Hills, CA 95762","$90,000 - $100,000 a year",Helm360,1 day ago,El Dorado Hills,CA 95762,CA 95762,CA,95762.0,Data Analyst,"$90,000","$100,000 a year","$100,000 a year","$100,000",2020/9/15,95762
55,Junior Data Analyst,"Sacramento, CA 95827","$70,000 - $85,000 a year",Course Hero,14 days ago,Sacramento,CA 95827,CA 95827,CA,95827.0,Data Analyst,"$70,000","$85,000 a year","$85,000 a year","$85,000",2020/9/2,95827
56,Data Analyst IInew,"Modesto, CA 95354","$64,800 - $73,200 a year","Biocept, Inc.",Today,Modesto,CA 95354,CA 95354,CA,95354.0,Data Analyst,"$64,800","$73,200 a year","$73,200 a year","$73,200",2020/9/16,95354
57,Data Analyst Temporarynew,"Morgan Hill, CA","$80,000 - $90,000 a year",Pyramid,Just posted,Morgan Hill,CA,CA,CA,NaN,Data Analyst,"$80,000","$90,000 a year","$90,000 a year","$90,000",2020/9/16,nan
58,Jr. Data Analyst,"Poway, CA 92064",$19 - $26 an hour,Sensor Tower,15 days ago,Poway,CA 92064,CA 92064,CA,92064.0,Data Analyst,$19,$26 an hour,$26 an hour,$26,2020/9/1,92064

In [ ]:
dfdate= job_convert['zi'].astype(str).str.split('/',expand=True)
dfdate.columns = ['Zip']

In [70]:
newdf = job_convert[['job_Title','company','location','formatted_date','city','state','Zip_code','job_type','low_range','High_range']].copy()
newdf

,job_Title,company,location,formatted_date,city,state,Zip_code,job_type,low_range,High_range
0,Business Systems Data Analystnew,Advantmed,"El Dorado Hills, CA 95762",2020/9/16,El Dorado Hills,CA,95762,Data Analyst,"$90,000","$100,000"
1,Senior Data Analyst (Healthcare and HEDIS expe...,Acer Service Corporation,"Sacramento, CA 95827",2020/9/2,Sacramento,CA,95827,Data Analyst,"$70,000","$85,000"
2,Data Analyst,Ursus,"Modesto, CA 95354",2020/8/16,Modesto,CA,95354,Data Analyst,"$64,800","$73,200"
3,Data Analyst - 017832new,Patra Corporation,"Morgan Hill, CA",2020/9/11,Morgan Hill,CA,nan,Data Analyst,"$80,000","$90,000"
4,Data Analystnew,Standard Homeopathic Company / Hyland's,"Poway, CA 92064",2020/9/11,Poway,CA,92064,Data Analyst,$19,$26
5,Data Analyst,Heritage Community Credit Union,"Redwood City, CA 94063 (Downtown area)",2020/9/2,Redwood City,CA,94063,Data Analyst,"Up to $80,000 a year",NaN
6,Marketing Specialist & Data Analystnew,Midland Credit Management,"San Diego, CA 92121 (Sorrento Valley area)",2020/9/11,San Diego,CA,92121,Data Analyst,"$90,000","$100,000"
7,Data Analyst,E.&J. Gallo Winery,"Pleasanton, CA",2020/8/16,Pleasanton,CA,nan,Data Analyst,"$70,000","$85,000"
8,Sales Data Analystnew,Amphenol Advanced Sensors,"San Francisco, CA",2020/9/15,San Francisco,CA,nan,Data Analyst,"$64,800","$73,200"
9,Data Analystnew,Helm360,"El Dorado Hills, CA 95762",2020/9/15,El Dorado Hills,CA,95762,Data Analyst,"$80,000","$90,000"
10,Junior Data Analyst,Course Hero,"Sacramento, CA 95827",2020/9/2,Sacramento,CA,95827,Data Analyst,$19,$26
11,Data Analyst IInew,"Biocept, Inc.","Modesto, CA 95354",2020/9/16,Modesto,CA,95354,Data Analyst,"Up to $80,000 a year",NaN
12,Data Analyst Temporarynew,Pyramid,"Morgan Hill, CA",2020/9/16,Morgan Hill,CA,nan,Data Analyst,"$90,000","$100,000"
13,Jr. Data Analyst,Sensor Tower,"Poway, CA 92064",2020/9/1,Poway,CA,92064,Data Analyst,"$70,000","$85,000"
14,Data Operations Analystnew,Express Employment Professionals,"Redwood City, CA 94063 (Downtown area)",2020/9/16,Redwood City,CA,94063,Data Analyst,"$64,800","$73,200"
15,Business Systems Data Analystnew,Advantmed,"San Diego, CA 92121 (Sorrento Valley area)",2020/9/16,San Diego,CA,92121,Data Analyst,"$80,000","$90,000"
16,Senior Data Analyst (Healthcare and HEDIS expe...,Acer Service Corporation,"Pleasanton, CA",2020/9/2,Pleasanton,CA,nan,Data Analyst,$19,$26
17,Data Analyst,Ursus,"San Francisco, CA",2020/8/16,San Francisco,CA,nan,Data Analyst,"Up to $80,000 a year",NaN
18,Data Analyst - 017832new,Patra Corporation,"El Dorado Hills, CA 95762",2020/9/11,El Dorado Hills,CA,95762,Data Analyst,"$90,000","$100,000"
19,Data Analystnew,Standard Homeopathic Company / Hyland's,"Sacramento, CA 95827",2020/9/11,Sacramento,CA,95827,Data Analyst,"$70,000","$85,000"
20,Data Analyst,Heritage Community Credit Union,"Modesto, CA 95354",2020/9/2,Modesto,CA,95354,Data Analyst,"$64,800","$73,200"
21,Marketing Specialist & Data Analystnew,Midland Credit Management,"Morgan Hill, CA",2020/9/11,Morgan Hill,CA,nan,Data Analyst,"$80,000","$90,000"
22,Data Analyst,E.&J. Gallo Winery,"Poway, CA 92064",2020/8/16,Poway,CA,92064,Data Analyst,$19,$26
23,Sales Data Analystnew,Amphenol Advanced Sensors,"Redwood City, CA 94063 (Downtown area)",2020/9/15,Redwood City,CA,94063,Data Analyst,"Up to $80,000 a year",NaN
24,Data Analystnew,Helm360,"San Diego, CA 92121 (Sorrento Valley area)",2020/9/15,San Diego,CA,92121,Data Analyst,"$90,000","$100,000"
25,Junior Data Analyst,Course Hero,"Pleasanton, CA",2020/9/2,Pleasanton,CA,nan,Data Analyst,"$70,000","$85,000"
26,Data Analyst IInew,"Biocept, Inc.","San Francisco, CA",2020/9/16,San Francisco,CA,nan,Data Analyst,"$64,800","$73,200"
27,Data Analyst Temporarynew,Pyramid,"El Dorado Hills, CA 95762",2020/9/16,El Dorado Hills,CA,95762,Data Analyst,"$80,000","$90,000"
28,Jr. Data Analyst,Sensor Tower,"Sacramento, CA 95827",2020/9/1,Sacramento,CA,95827,Data Analyst,$19,$26
29,Data Operations Analystnew,Express Employment Professionals,"Modesto, CA 95354",2020/9/16,Modesto,CA,95354,Data Analyst,"Up to $80,000 a year",NaN
30,Business Systems Data Analystnew,Advantmed,"Morgan Hill, CA",2020/9/16,Morgan Hill,CA,nan,Data Analyst,"$90,000","$100,000"
31,Senior Data Analyst (Healthcare and HEDIS expe...,Acer Service Corporation,"Poway, CA 92064",2020/9/2,Poway,CA,92064,Data Analyst,"$70,000","$85,000"
32,Data Analyst,Ursus,"Redwood City, CA 94063 (Downtown area)",2020/8/16,Redwood City,CA,94063,Data Analyst,"$64,800","$73,200"
33,Data Analyst - 017832new,Patra Corporation,"San Diego, CA 92121 (Sorrento Valley area)",2020/9/11,San Diego,CA,92121,Data Analyst,"$80,000","$90,000"
34,Data Analystnew,Standard Homeopathic Company / Hyland's,"Pleasanton, CA",2020/9/11,Pleasanton,CA,nan,Data Analyst,$19,$26
35,Data Analyst,Heritage Community Credit Union,"San Francisco, CA",2020/9/2,San Francisco,CA,nan,Data Analyst,"Up to $80,000 a year",NaN
36,Marketing Specialist & Data Analystnew,Midland Credit Management,"El Dorado Hills, CA 95762",2020/9/11,El Dorado Hills,CA,95762,Data Analyst,"$90,000","$100,000"
37,Data Analyst,E.&J. Gallo Winery,"Sacramento, CA 95827",2020/8/16,Sacramento,CA,95827,Data Analyst,"$70,000","$85,000"
38,Sales Data Analystnew,Amphenol Advanced Sensors,"Modesto, CA 95354",2020/9/15,Modesto,CA,95354,Data Analyst,"$64,800","$73,200"
39,Data Analystnew,Helm360,"Morgan Hill, CA",2020/9/15,Morgan Hill,CA,nan,Data Analyst,"$80,000","$90,000"
40,Junior Data Analyst,Course Hero,"Poway, CA 92064",2020/9/2,Poway,CA,92064,Data Analyst,$19,$26
41,Data Analyst IInew,"Biocept, Inc.","Redwood City, CA 94063 (Downtown area)",2020/9/16,Redwood City,CA,94063,Data Analyst,"Up to $80,000 a year",NaN
42,Data Analyst Temporarynew,Pyramid,"San Diego, CA 92121 (Sorrento Valley area)",2020/9/16,San Diego,CA,92121,Data Analyst,"$90,000","$100,000"
43,Jr. Data Analyst,Sensor Tower,"Pleasanton, CA",2020/9/1,Pleasanton,CA,nan,Data Analyst,"$70,000","$85,000"
44,Data Operations Analystnew,Express Employment Professionals,"San Francisco, CA",2020/9/16,San Francisco,CA,nan,Data Analyst,"$64,800","$73,200"
45,Business Systems Data Analystnew,Advantmed,"El Dorado Hills, CA 95762",2020/9/16,El Dorado Hills,CA,95762,Data Analyst,"$80,000","$90,000"
46,Senior Data Analyst (Healthcare and HEDIS expe...,Acer Service Corporation,"Sacramento, CA 95827",2020/9/2,Sacramento,CA,95827,Data Analyst,$19,$26
47,Data Analyst,Ursus,"Modesto, CA 95354",2020/8/16,Modesto,CA,95354,Data Analyst,"Up to $80,000 a year",NaN
48,Data Analyst - 017832new,Patra Corporation,"Morgan Hill, CA",2020/9/11,Morgan Hill,CA,nan,Data Analyst,"$90,000","$100,000"
49,Data Analystnew,Standard Homeopathic Company / Hyland's,"Poway, CA 92064",2020/9/11,Poway,CA,92064,Data Analyst,"$70,000","$85,000"
50,Data Analyst,Heritage Community Credit Union,"Redwood City, CA 94063 (Downtown area)",2020/9/2,Redwood City,CA,94063,Data Analyst,"$64,800","$73,200"
51,Marketing Specialist & Data Analystnew,Midland Credit Management,"San Diego, CA 92121 (Sorrento Valley area)",2020/9/11,San Diego,CA,92121,Data Analyst,"$80,000","$90,000"
52,Data Analyst,E.&J. Gallo Winery,"Pleasanton, CA",2020/8/16,Pleasanton,CA,nan,Data Analyst,$19,$26
53,Sales Data Analystnew,Amphenol Advanced Sensors,"San Francisco, CA",2020/9/15,San Francisco,CA,nan,Data Analyst,"Up to $80,000 a year",NaN
54,Data Analystnew,Helm360,"El Dorado Hills, CA 95762",2020/9/15,El Dorado Hills,CA,95762,Data Analyst,"$90,000","$100,000"
55,Junior Data Analyst,Course Hero,"Sacramento, CA 95827",2020/9/2,Sacramento,CA,95827,Data Analyst,"$70,000","$85,000"
56,Data Analyst IInew,"Biocept, Inc.","Modesto, CA 95354",2020/9/16,Modesto,CA,95354,Data Analyst,"$64,800","$73,200"
57,Data Analyst Temporarynew,Pyramid,"Morgan Hill, CA",2020/9/16,Morgan Hill,CA,nan,Data Analyst,"$80,000","$90,000"
58,Jr. Data Analyst,Sensor Tower,"Poway, CA 92064",2020/9/1,Poway,CA,92064,Data Analyst,$19,$26

In [71]:
newdf.to_csv('AIP_indeed.csv',index=False)